Unicode
CyberBoardPBEM/cbwindows pull request #116
Opened 2023-05-14 03:25 UTC by wsu-cb

This is the beginning of Unicode support.  It enables CB to build and run in Unicode mode.  Note that the conversions between Unicode and ANSI only handle ANSI chars.  Full conversions are planned to be implemented using wxWidgets.  Adding wxWidgets is the next step.

2023-07-03 21:28 UTC, wsu-cb commented
Dale,
This PR now has `wxWidgets` as a submodule and `CMakeLists.txt` files to build using CMake.  However, I don't know how to set up GitHub to use either git submodules or CMake builds.  Do you know how to set that up?  If not, I will have to start hunting through GitHub documentation.

I have also updated the `.vcxproj` files to use wxWidgets as built by MSVS CMake integration in case anyone wants to continue using the traditional MSVS IDE.  I'm not sure whether it's worth maintaining both build systems long term, but I also didn't want to drop `.vcxproj` just yet.

Note that wxWidgets master branch has dropped ANSI support, so the current CB can't be built with ANSI any more.  Also, I have only worked through `x64 Debug` builds; I am putting off working on `x86` and `Release` builds until GitHub can build `x64 Debug`.

2023-07-08 15:45 UTC, DLLarson commented
Hi Bill,

>I don't know how to set up GitHub to use either git submodules...

If you look at the failed build's checkout area you'll see this:

```
Run actions/checkout@v2
  with:
    repository: CyberBoardPBEM/cbwindows
    token: ***
    ssh-strict: true
    persist-credentials: true
    clean: true
    fetch-depth: 1
    lfs: false
    submodules: false
    set-safe-directory: true
```
I think if you set `submodules` to `true` it will also checkout the submodules. Also the checkout action is now at `v3` so we should probably bump that up.

So change workflow in `main.yml` to:

```
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3
      with:
        submodules: 'true'

```

Here are the docs for the `checkout` action:

https://github.com/marketplace/actions/checkout

>or CMake builds. Do you know how to set that up? If not, I will have to start hunting through GitHub documentation.

Here are the docs for using CMake with GitHub actions:

https://github.com/marketplace/actions/cmake-action

I've never used the action myself but it seems pretty straight forward.

-Dale

2023-07-11 15:34 UTC, DLLarson requested changes
Not really reviewing yet. See comment about automatic builds failing.

2023-07-12 01:23 UTC, wsu-cb commented
> Not really reviewing yet. See comment about automatic builds failing.

I agree.  The review request on July 3 was because I didn't know how else to draw your attention to my July 3 comment.  I now suspect @ would have worked.

2023-07-12 01:26 UTC, DLLarson commented
Not a problem. It did what you intended!
-Dale

2023-07-15 05:41 UTC, wsu-cb commented
I realized that wxWidgets's workflows provide a lot of clues for how to use git submodules and CMake.  In particular, the GitHub CMake Action does not document any way to select between x64 and x86.  On the other hand, wxWidgets uses somewhat more generic actions that do appear to allow both x64 and x86 builds.  GitHub can now produce an x64-Debug build of CB that uses wxWidgets for converting between Windows-1252 and UTF-16 character encodings.

2023-07-15 05:46 UTC, wsu-cb commented
I hope you are willing to begin reviewing the code now that x64-Debug builds even though Release and x86 builds are not yet available.

2023-07-15 18:07 UTC, DLLarson commented
>I hope you are willing to begin reviewing the code now that x64-Debug builds even though Release and x86 builds are not yet available.

I'm curious if x86 is buildable from VS or is the issue just that CMake hasn't been fed a proper toolchain description for x86 yet. Can I assume that reviewing the source code for one model should cover all models? With a review covering over 200 files I'd like to not do it all twice. ;)

-Dale

2023-07-17 04:16 UTC, wsu-cb commented
As you can see from the Checks above, as of https://github.com/CyberBoardPBEM/cbwindows/commit/5b65d3429e7370655170c9c443baa35f91cc018f, this PR is able to build all four x64/x86-Debug/Release using the workflow now.  However, I haven't figured out how the workflow is supposed to report its result to GitHub, and GitHub appears to think the Check is still in progress.

As for building using MSVS, that is actually one of the things I think need review here.  Because the current code calls wxWidgets, the `.vcxproj` files now need to know where the wxWidgets include and lib files are.  Unfortunately, wxWidgets puts files in different places depending on whether it is built using CMake or nmake/IDE.  Because I think using CMake is the long-term future, as well as the simplest way to make the GitHub workflows work, I have configured the `.vcxproj` files to use wxWidgets as built by CMake.  However, this means that MSVS IDE can only build the `.sln` if wxWidgets has already been built by CMake, and the most convenient way to do that is to use CMake to build the whole CB.  (The alternative would be to configure the `.vcxproj` files to match the nmake/IDE wxWidgets layout, and build wxWidgets that way as a separate pre-CB build step.  There is another possibility that I haven't investigated because I'm not actually sure it will work:  modify the CB `.sln` to use the wxWidgets `.vcxproj` files.)  MSVS (with "C++ CMake tools for Windows" component installed) actually understands the `CMakeLists.txt` pretty well.  However, it does require that the devloper open the FOLDER rather than the `.sln`, and also to wait a non-trivial time for MSVS to process the CMake enough to populate the MSVS `Build` menu.  What I have committed is my preferred approach, but I don't know if you will agree.

2023-07-19 03:48 UTC, wsu-cb commented
I finally figured out that I need to still have a dummy version the old `jobs.build` as part of the `main.yml` to satisfy GitHub.  I suspect there is a setting on the repository that I can't see (or change) that should be changed to replace `jobs.build` with the new `jobs.build-matrix` I have added to `main.yml`, and then we can remove `jobs.build` from `main.yml`.  Or maybe `jobs.build` must be replaced with all four of the sub-jobs that `jobs.build-matrix` creates; that would be slightly annoying, but I suspect that's what's actually required.

2023-07-24 18:55 UTC, DLLarson commented
It looks like churn on the PR has stopped. Is it ready for me to start going through the code?

-Dale

2023-07-25 00:32 UTC, wsu-cb commented
As noted in https://github.com/CyberBoardPBEM/cbwindows/pull/116#issuecomment-1641371681, I suspect there is a setting to which I do not have permissions that expects a Check named `build`.  However, it seems reasonable to me to replace that single check with the four `build x86/x64-Debug/Release` variants.  If I am correct, do you want to change that setting and then update the PR to remove `build` before you start your review?

2023-07-25 16:34 UTC, DLLarson commented
> I suspect there is a setting to which I do not have permissions that expects a Check named `build`. However, it seems reasonable to me to replace that single check with the four `build x86/x64-Debug/Release` variants. If I am correct, do you want to change that setting and then update the PR to remove `build` before you start your review?

I'm not clear on the matrix stuff but after looking at:

https://ncorti.com/blog/howto-github-actions-build-matrix

and this:

https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs

I'm wondering what would happen if you removed the `build` job and replace the name of the matrix strategy as simply `build` rather than `build-matrix`. Plus I'm not clear on the use of `name: build ${{ matrix.arch }}-${{ matrix.config }}` definition prior to `strategy`. I don't see it in any examples for matrix strategy jobs or referenced in the steps below as `build-matrix.name`

I think we should work through this problem before preceding with the code itself.

-Dale

2023-07-31 16:05 UTC, DLLarson commented
Hi Bill,

I did some poking around on the GitHub actions stuff and I have tweaked our workflow so it seems to work. I figured this out by forking your fork of the Cyberboard repo and working within that repo alone.

```
name: Check Cyberboard Commit

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  # This allows this workflow to be manually run from the repository's GitHub Actions feature
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: windows-2022
    name: build ${{ matrix.arch }}-${{ matrix.config }}
    strategy:
      matrix:
        arch: [ x64, x86 ]
        config: [ Debug, Release ]
        include:
          - arch: x64
            arch_vsdev: amd64
          - arch: x86
            arch_vsdev: x86
          - config: Debug
            cmake_build_type: Debug
          - config: Release
            cmake_build_type: RelWithDebInfo

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    # copied from wxWidgets/.../ci_cmake.yml
    # required for CMake to find Ninja
    - name: "[Windows] Set up MSVC Developer Command Prompt"
      if: runner.os == 'Windows'
      uses: wxWidgets/gha-setup-vsdevenv@ac61ecb4b05909261f8f375601c0e15aabdd9f10
      with:
        arch: ${{ matrix.arch_vsdev }}

    - name: CMake Configure and Build ${{ matrix.arch }}-${{ matrix.config }}
      run: |
        mkdir out\build\${{ matrix.arch }}-${{ matrix.config }}
        cmake -G Ninja -B out\build\${{ matrix.arch }}-${{ matrix.config }} -DCMAKE_BUILD_TYPE=${{ matrix.cmake_build_type }}
        cmake --build out\build\${{ matrix.arch }}-${{ matrix.config }}
```

Just replace the contents of `.github/workflowa/main.yml` with the above. Note that I also added a trigger that allows us to manually run the workflow within our local forks on arbitrary topic branches without submitting a pull request against `master`.

Once this is put into place and you see if it works I'll start the code inspection.

-Dale

2023-08-01 02:12 UTC, wsu-cb commented
According to https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/, your change should have given my repo a "Run workflow" button, but my repo doesn't seem to have it (see below).  Also, applying that version of `main.yml` has caused this PR to again have the hanging "build" Check.

![image](https://github.com/CyberBoardPBEM/cbwindows/assets/69879726/16db74a8-5f28-484f-95cf-9efd37ca617e)

2023-08-01 14:15 UTC, DLLarson commented
>Also, applying that version of main.yml has caused this PR to again have the hanging "build" Check.

For reference... the status shown in the PR comment section says:

>build Expected — Waiting for status to be reported

This is just plain weird. If I click on the Actions results at repo `CyberBoardPBEM/cbwindows` I see a successful build without the waiting thing:

https://github.com/CyberBoardPBEM/cbwindows/actions/runs/5721588657

Yet it shows this "waiting" status in the PR comments section. Even stranger is that there seems to be no way to actually get anymore information. I don't see anything about it in the run results in the Actions section.

>your change should have given my repo a "Run workflow" button, but my repo doesn't seem to have it (see below).

Here's what my fork shows me:

![image](https://github.com/CyberBoardPBEM/cbwindows/assets/175455/dde0f5d9-434c-4823-827f-57f6882b0142)

I get fully clean builds with no waiting status anomalies.

Perhaps Github is disabling it for you because your branch was submitted as a PR? Could you try creating a duplicate branch and select it as the default branch for your repo and see if it shows up then? This is the state of my fork.

Plus, could you compare your fork's repo Settings/Actions with mine (which are mostly defaulted values)?:

![image](https://github.com/CyberBoardPBEM/cbwindows/assets/175455/7e106dcd-159e-4554-9849-914f84224809)

-Dale

2023-08-01 14:21 UTC, DLLarson commented
>Yet it shows this "waiting" status in the PR comments section. Even stranger is that there seems to be no way to actually get anymore information. I don't see anything about it in the run results in the Actions section.

I just found this by googling the message:

https://stackoverflow.com/questions/52200096/github-pull-request-waiting-for-status-to-be-reported

and this:

https://github.com/orgs/community/discussions/26698

Which might shed some light on the issue.

-Dale

2023-08-02 00:31 UTC, wsu-cb commented
> Perhaps Github is disabling it for you because your branch was submitted as a PR? Could you try creating a duplicate branch and select it as the default branch for your repo and see if it shows up then? This would match the state of my fork.
> 

As requested, I created a duplicate branch with the `dispatch_workflow` and made it the default branch.  At that point, I get the "Run workflow" button.  I switched the default branch back to `master`, and the "Run workflow" button is gone again.  My own hypothesis is that the button isn't missing because the branch is a PR, but rather because the GitHub Actions page isn't branch-specific, and therefore has to "blindly" pick a branch to check for `dispatch_workflow`.  If it only checks one branch, it makes sense for it to be the default branch.

2023-08-02 00:36 UTC, wsu-cb commented
> I may have found the `master` branch "rule" in the main repository that caused the status wait problem. These docs helped:
> 
> https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/managing-a-branch-protection-rule
> 
> I removed the rule that referenced `build` so please try again.
> 
> -Dale

Unfortunately, now the PR says all four builds are "In progress" even though the "Actions" page says all the builds are complete and successful.

2023-08-02 00:47 UTC, wsu-cb commented
> Unfortunately, now the PR says all four builds are "In progress" even though the "Actions" page says all the builds are complete and successful.

Wow!  Now the checks report success.  There seems to have been a difference of close to half an hour between the builds completing and the PR noticing.

Since it appears that this may work after all, I will apply the `--fixup` commit and push again.  Let's see what happens...

2023-08-02 01:11 UTC, wsu-cb commented
> Wow! Now the checks report success. There seems to have been a difference of close to half an hour between the builds completing and the PR noticing.

And this time there doesn't seem to have been much, if any, delay in detecting completion.

In any case, I think this PR is ready for review.

2023-08-02 13:52 UTC, DLLarson commented
>And this time there doesn't seem to have been much, if any, delay in detecting completion.

Pretty janky stuff. Slowly we're learning the idiosyncrasies of the Github Actions system. I'm glad they have it available but it does have a learning curve do to its declarative nature.

>In any case, I think this PR is ready for review.

Excellent! So I guess we should push the "Ready for review" button then. I'll do that now.

I'll start nibbling away at it. There's lots of files to go through so I imagine it will take some time. 

-Dale

2023-08-02 13:53 UTC, DLLarson approved these changes

2023-08-10 18:39 UTC, DLLarson requested changes
Well I'm done and that was a heap of work. Fortunately many of the changes have simple boilerplate like substitutions.

In a nutshell I see that all string operations, including those that access resources, are funneled through the `CB:string` class to localize future string changes to this class. So I'm expecting that these unicode changes won't have to revisit these 200+ files for another round of inspections.

Also I've seen many improvements that many newer features of C++ are working their way into the code. This is good stuff. I like the increase in type safety that comes with it.

However, I still don't have a linked version of the programs to take the program for a spin. I think some additional steps to make the process of cloning and building the code for debugging and testing for those outside a batch build environment are needed.

All-in-all you've done a helluva lot of work here that really preps the system for a wxWidgets future. Very impressive!

-Dale


-Dale

2023-08-10 18:39 UTC, DLLarson commented on .github/workflows/main.yml
I think it would be nice to provide some instructions on building the submodule version of wxWidgets such that the VC solutions are ready to build. Or some simple instruction to prepare a CMake build. I think the solution files is more desirable though since that's what normal developer types would use to also debug the code.

2023-08-10 18:39 UTC, DLLarson commented on .github/workflows/main.yml
I built the static versions of wxWidgets from its submodule location for debug and release using wxWidgets `nmake` procedure for msw. My expectation was that CB's VC++ solution would then correctly locate the associated include, lib, etc... files because it lives in a relative directory of the main project.

What happened is I got this error:

```
Build started...
1>------ Build started: Project: CBDesign, Configuration: DebugU Win32 ------
1>StdAfx.cpp
1>D:\Dev\CBoard\G\cbwindows\deps\wxWidgets\include\wx\platform.h(159,10): fatal  error C1083: Cannot open include file: 'wx/setup.h': No such file or directory
1>Done building project "CBDsgn32.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
========== Build started at 1:16 PM and took 05.355 seconds ==========
```

It doesn't find the essential files. I think it is really important not to have to edit the solution's projects after cloning the source for a build.

2023-08-11 02:14 UTC, wsu-cb commented on GP/GamDoc.h
> +template<typename CharT>
This is a specialization of `std::formatter<>` to `enable std::format()` to display readable strings instead of the (numeric) values of `enum PlacePos`.  Since the actual displayed data is really a string (not a number), the standard format specification for strings should be available, so the subclassing provides a convenient way to implement `std::formatter<PlacePos>::parse()` to behave the same way as `std::formatter<std::string>::parse()` (by actually calling `std::formatter<std::string>::parse()` with `using BASE::parse`.)  Since this uses private inheritance, the subclassing is just an implementation detail, not something that is adjusting namespace or anything like that.

2023-08-11 17:02 UTC, DLLarson commented on GP/GamDoc.h
> +template<typename CharT>
Cool! Thanks for clarifying that. Much for me to learn about evolving C++.

-Dale

2023-08-15 04:58 UTC, wsu-cb commented
It looks like it's going to be several more days before I get back to this.

2023-08-15 21:45 UTC, DLLarson commented
>It looks like it's going to be several more days before I get back to this.

That's fine with me. I just didn't want to have you waiting on me.

I appreciate all your efforts regardless of when they are offered. CB's lucky to have you!

-Dale

2023-08-21 03:49 UTC, wsu-cb commented on GP/Editnocv.cpp
> +            class RAII_GlobalLock
I agree that, at some point, I should update clipboard use.  However, that's not something I'm currently thinking about.

2023-08-21 03:52 UTC, wsu-cb commented on .github/workflows/main.yml
Please see if what I put in `README.md` explains how to build successfully.

2023-08-21 04:16 UTC, wsu-cb commented on GM/VwBitedt.cpp
> +{
done

2023-08-22 02:05 UTC, wsu-cb commented on GShr/LibMfc.cpp
I'm working on this now, but I have a question.  I modified the `DibApi.*` files, but now I notice that they weren't originally your files; they were apparently copied from the MFC source code.  So is it acceptable to modify them, or should I undo my changes?  If changing them is OK, what, if anything, do we do with the copyright notices?

2023-08-23 03:36 UTC, wsu-cb commented on GShr/LibMfc.cpp
`MD5.*` is also third-party code, but its license gives permission to "make and use derivative works provided that ...", so I think we are on safe legal ground to tweak it.

2023-08-26 15:47 UTC, DLLarson commented on GShr/LibMfc.cpp
You raise an excellent point about the origins of DibApi.*. When using it in an MFC context it was fine and dandy. But targeting a different framework and carrying it along seems iffy. 

Is there any support for DIB processing that is part of the wxWidgets framework that we can replace this with?

>MD5.* is also third-party code, but its license gives permission to "make and use derivative works provided that ...", so I think we are on safe legal ground to tweak it.

As you say MD5.* is fine.

-Dale

2023-08-26 16:27 UTC, DLLarson commented on .github/workflows/main.yml
Here's what I did and what happened...

```
D:\Dev\CBoard\G\cbwindows>git checkout origin/pr/116 -b pr-116
Switched to a new branch 'pr-116'
M       deps/wxWidgets
Branch 'pr-116' set up to track remote branch 'pr/116' from 'origin'.
### NOTE THAT I HAD TO FIGURE OUT THIS NEXT STEP BY GOOGLING.
### IT SHOULD BE PORVIDED SO AS NOT TO DISCOURAGE THOSE WHO AREN'T
### SAVY WITH GIT SUBMODULES.
D:\Dev\CBoard\G\cbwindows>git submodule update --init --recursive
Submodule path 'deps/wxWidgets/3rdparty/catch': checked out '18bf9ebaefbefb3018528138a85322cff5aba93e'
Submodule path 'deps/wxWidgets/3rdparty/nanosvg': checked out 'ccdb1995134d340a93fb20e3a3d323ccb3838dd0'
Submodule path 'deps/wxWidgets/3rdparty/pcre': checked out '5b934c2a6770c05ae3e9bc5f63e0ed5da098b08b'
Submodule path 'deps/wxWidgets/src/expat': checked out '23b7f47ef6043929b648de53ac04024c4ac7afcb'
Submodule path 'deps/wxWidgets/src/jpeg': checked out '852493611506076fd9ad931d35bf1c3cc5b5a9c3'
Submodule path 'deps/wxWidgets/src/png': checked out 'd675c669c8250b7da55747c81a5bd01504449e6e'
Submodule path 'deps/wxWidgets/src/stc/lexilla': checked out '7cab74cefa54851e99b8c06bd6e2cd659b4958ae'
Submodule path 'deps/wxWidgets/src/stc/scintilla': checked out 'b662e55b3d8143bdad94e9a373679c0bfa3f834d'
Submodule path 'deps/wxWidgets/src/tiff': checked out 'af035310bddac3e2f58ae0a330bc6ef168e180f1'
Submodule path 'deps/wxWidgets/src/zlib': checked out 'a6c8900ecb9da7ac0d2a67467258fd4c1814b780'

D:\Dev\CBoard\G\cbwindows>cmake -G Ninja -B out/build/x64-Debug
CMake Deprecation Warning at CMakeLists.txt:3 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- The CXX compiler identification is MSVC 19.37.32822.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.37.32822/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:36 (add_subdirectory):
  The source directory

    D:/Dev/CBoard/G/cbwindows/deps/wxWidgets

  does not contain a CMakeLists.txt file.


-- Configuring incomplete, errors occurred!

D:\Dev\CBoard\G\cbwindows>
```
Seeing the above I'm asking myself: what does `<working_copy>` mean?

Approaching this as a rookie, I'm now stuck. I think we need more explicit step-by-step instructions to bootstrap a new contributor without scaring them off with cryptic (to one not practiced in the `CMake` arts that is) problems with the build. Including the manner how the submodule source code gets populated.

-Dale

2023-08-26 16:28 UTC, DLLarson commented on GP/Editnocv.cpp
> +            class RAII_GlobalLock
>However, that's not something I'm currently thinking about.

OK.

2023-08-26 20:16 UTC, wsu-cb commented on .github/workflows/main.yml
<working_copy> refers to the root directory of the cbwindows git working copy.  As near as I can tell from your log, you interpreted it correctly.  What does `dir D:\Dev\CBoard\G\cbwindows\deps\wxWidgets` report?  I'm really puzzled that you are getting an error that says it doesn't contain `CMakeLists.txt`.

2023-08-26 21:20 UTC, DLLarson commented on .github/workflows/main.yml
>What does dir D:\Dev\CBoard\G\cbwindows\deps\wxWidgets report?

It says this:

```
D:\Dev\CBoard\G\cbwindows>dir deps\wxWidgets
 Volume in drive D is Data
 Volume Serial Number is B6BB-63B8

 Directory of D:\Dev\CBoard\G\cbwindows\deps\wxWidgets

08/26/2023  11:11 AM    <DIR>          .
08/26/2023  11:11 AM    <DIR>          ..
08/26/2023  11:11 AM    <DIR>          3rdparty
08/26/2023  11:11 AM    <DIR>          src
               0 File(s)              0 bytes
               4 Dir(s)  149,032,185,856 bytes free

D:\Dev\CBoard\G\cbwindows>
```

2023-08-26 22:11 UTC, wsu-cb commented on .github/workflows/main.yml
That is seriously incomplete.  I get
```
 Directory of g:\cyberboard\github\cbwindows\deps\wxWidgets

07/04/2023  12:18 PM    <DIR>          .
07/04/2023  12:18 PM    <DIR>          ..
07/04/2023  12:13 PM    <DIR>          .circleci
07/04/2023  12:13 PM             3,143 .cirrus.yml
07/04/2023  12:13 PM               302 .editorconfig
07/04/2023  12:13 PM             2,267 .git-blame-ignore-revs
07/04/2023  12:13 PM             1,433 .gitattributes
07/04/2023  12:13 PM    <DIR>          .github
07/04/2023  12:13 PM             8,517 .gitignore
07/04/2023  12:13 PM             1,112 .gitmodules
07/04/2023  12:13 PM             4,229 .mailmap
07/04/2023  12:13 PM    <DIR>          3rdparty
07/04/2023  12:13 PM            25,004 acinclude.m4
07/04/2023  12:13 PM             1,463 aclocal.m4
07/04/2023  12:13 PM             3,359 appveyor.yml
07/04/2023  12:13 PM    <DIR>          art
07/04/2023  12:13 PM           238,494 autoconf_inc.m4
07/04/2023  12:13 PM                52 autogen.sh
07/04/2023  12:14 PM    <DIR>          build
07/04/2023  12:13 PM             4,274 CMakeLists.txt
07/04/2023  12:14 PM            49,938 config.guess
07/04/2023  12:14 PM            35,819 config.sub
07/04/2023  12:14 PM         1,257,340 configure
07/04/2023  12:14 PM           297,926 configure.in
07/04/2023  12:14 PM    <DIR>          demos
07/04/2023  12:14 PM            15,884 descrip.mms
07/04/2023  12:14 PM    <DIR>          distrib
07/04/2023  12:15 PM    <DIR>          docs
07/04/2023  12:15 PM    <DIR>          include
07/04/2023  12:16 PM             5,834 install-sh
07/04/2023  12:16 PM    <DIR>          interface
07/04/2023  12:16 PM    <DIR>          lib
07/04/2023  12:16 PM    <DIR>          locale
07/04/2023  12:13 PM         1,889,068 Makefile.in
07/04/2023  12:16 PM    <DIR>          misc
07/04/2023  12:16 PM               714 mkinstalldirs
07/04/2023  12:13 PM               675 README-GIT.md
07/04/2023  12:13 PM             4,128 README.md
07/04/2023  12:16 PM               570 regen
07/04/2023  12:17 PM    <DIR>          samples
07/04/2023  12:17 PM            23,169 setup.h.in
07/04/2023  12:17 PM            27,818 setup.h_vms
07/04/2023  12:18 PM    <DIR>          src
07/04/2023  12:18 PM    <DIR>          tests
07/04/2023  12:18 PM    <DIR>          utils
07/04/2023  12:18 PM               935 version-script.in
07/04/2023  12:18 PM             1,169 wx-config-inplace.in
07/04/2023  12:18 PM            49,995 wx-config.in
07/04/2023  12:18 PM             7,477 wxwidgets.props
07/04/2023  12:18 PM            38,996 wxwin.m4
              31 File(s)      4,001,104 bytes
              19 Dir(s)  51,388,420,096 bytes free
```

What does `git -C deps/wxWidgets status` report?  I get
```
$ git -C deps/wxWidgets/ status
HEAD detached at f50fb719e8
nothing to commit, working tree clean
```

My best guess is that `git submodule update --init --recursive` didn't work as expected.  I have never tried to add a submodule to an existing working copy using a PR before; I don't know what the right way to do that would be.  If you run a clean git clone from my repo `git clone https://github.com/wsu-cb/cbwindows.git --recurse-submodules -b unicode`, does following the build directions work?  If so, then once this PR is merged into `master`, `git clone https://github.com/CyberBoardPBEM/cbwindows.git --recurse-submodules` should work.

2023-08-27 14:00 UTC, DLLarson commented on .github/workflows/main.yml
>What does git -C deps/wxWidgets status report? 

I get a zillion deleted files.

I went into the wxWidgets directory and did the commmand `git reset --hard` and a bunch of files were restored. I wonder how it got in this state.

Now when I run your above command I get:
```
D:\Dev\CBoard\G\cbwindows>git -C deps/wxWidgets/ status
HEAD detached at f50fb719e8
nothing to commit, working tree clean

D:\Dev\CBoard\G\cbwindows>
```
So that looks like it fixed it.

I just reran the `cmake -G Ninja -B out/build/x64-Debug` command and now it completes without issue. Next I ran the actual build and it completes as well. I can run the two CB*.exe applications just fine (although the layout looks a bit different but that's not important here.

-Dale

2023-08-27 14:03 UTC, DLLarson commented on .github/workflows/main.yml
I still think the build and debug instructions could use a bit more hand holding. Maybe even add a batch file that builds all configurations locally for convenience sake.

I'll continue to poke around with the applications some to see if there are some side effects to this PR.

2023-08-27 14:36 UTC, wsu-cb commented on .github/workflows/main.yml
> I went into the wxWidgets directory and did the commmand `git reset --hard` and a bunch of files were restored. I wonder how it got in this state.

I have no idea.  It would have been slightly plausible if `wxWidgets` was entirely empty, but to have a few files is really weird.

> I just reran the `cmake -G Ninja -B out/build/x64-Debug` command and now it completes without issue. Next I ran the actual build and it completes as well. I can run the two CB*.exe applications just fine (although the layout looks a bit different but that's not important here.

It's definitely good that you can run now, and if you mean the layout changed relative to CB3.1, then indeed there have been some changes.  However, if you mean changes between before and after this PR, then could you please post screen shots of the differences?  I don't remember any reason for this PR to have changed anything.

2023-08-27 14:51 UTC, wsu-cb commented on GShr/LibMfc.cpp
> Is there any support for DIB processing that is part of the wxWidgets framework that we can replace this with? Perhaps there's another graphics package with a looser license (like MIT)?
> 

I would have to dig deeper into the implementation details of wxWidgets to determine if/where they use DIBs vs DDBs. 
 They have `wxImage`, which is a PLATFORM independent image, which maybe could be used instead of DIBs, but they require converting to `wxBitmap` for actual display (https://docs.wxwidgets.org/trunk/classwx_image.html).  On the other hand, that scheme doesn't sound so different from the DDB/DIB scheme.  Without doing any real study of the question, I could imagine relacing `CDib` with `wxImage` and `CBitmap` with `wxBitmap`.

Maybe removing DibApi.* should be my next major task.  If so, should that be part of this PR?  It's entirely out of the orginal scope, but the issue of the copyrights makes it seem like I shouldn't have entirely stayed out of that portion of the code.  Unfortunately, I don't think we should postpone this PR until after DibApi.* removal because my first attempt at doing so would require using wxWidgets, which is the major point of this PR.

2023-08-27 17:24 UTC, DLLarson commented on GShr/LibMfc.cpp
>Maybe removing DibApi.* should be my next major task. If so, should that be part of this PR?

I would say it's an entirely new PR. It has nothing to do with Unicode support. It's also great this PR had the additional "side effect" of starting the integration of wxWidgets so we gain all the build stuff for it so there is smoother sailing ahead for that work! The foundation is now in place.

-Dale

2023-08-27 17:29 UTC, DLLarson commented on .github/workflows/main.yml
>I don't remember any reason for this PR to have changed anything.

It just looked like the default toolbar positions for both apps seemed kind of spread around. I haven't wiped CB's registry settings is a long time so perhaps that's part of it. For now don't worry about it since I'm going to exercise this code for a few days. We'll see if anything worrisome shakes out.

-Dale

2023-08-29 13:55 UTC, DLLarson commented on .github/workflows/main.yml
Ok... I'll check that out later today.

2023-08-29 19:05 UTC, DLLarson requested changes
I've completed looking at the README mods and the addition of the build all batch file.

2023-08-29 19:05 UTC, DLLarson commented on build-all-configs.bat
I've added a few tweaks below to allow the user to adapt to a non-standard VS location. The script works for me regardless of my minor mods.

This simple script is super useful to get all things built quickly!

-Dale

2023-08-30 00:05 UTC, wsu-cb commented on build-all-configs.bat
> +call "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars32.bat"
My command prompt doesn't have a VSROOTDIR environment variable.  Where are you getting that variable from?

2023-08-30 00:07 UTC, wsu-cb commented on build-all-configs.bat
> +call "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars32.bat"
> My command prompt doesn't have a VSROOTDIR environment variable. Where are you getting that variable from?

Whoops.  I now see the message that suggests adding that variable to the .bat file.

2023-08-30 21:48 UTC, DLLarson commented
I've reviewed and tested the latest README and batch file and it works great!

In only three commands I get everything built plus it's super FAST!

```
git clone https://github.com/wsu-cb/cbwindows.git --recurse-submodules -b unicode
cd cbwindows
build-all-configs
```

It's a great stress free way to get up and running for developers.

Excellent work on top of the Unicode bootstrap heavy lift you did. It is a big step to arc the code into the future.

I kicked the tires running the various build targets and everything seems to be operating as it was before this work.

I'm ready to merge if you're comfortable with things. (Plus I know you want to do a final edit of the `README.md` file to remove the temporary git clone command.)

-Dale

2023-08-30 21:49 UTC, DLLarson approved these changes

2023-08-30 23:58 UTC, wsu-cb commented
> I'm ready to merge if you're comfortable with things. (Plus I know you want to do a final edit of the `README.md` file to remove the temporary git clone command.)
> 

I definitely need to do that particular cleanup.  However, assuming you don't object to `git push --force` being applied to this PR now, I would be inclined to also use `git rebase -i` to apply the `fixup` actions as well as the `git clone` cleanup.  Is that OK with you?

2023-08-31 00:58 UTC, DLLarson commented
>Is that OK with you?

Yep. Ping me when you're ready!

-Dale

2023-08-31 23:59 UTC, DLLarson approved these changes
Would you like a squash and commit or just to add all commits?

-Dale

2023-09-01 00:37 UTC, wsu-cb commented
> Would you like a squash and commit or just to add all commits?

I prefer to keep commits relatively small.  I would like to keep this in separate commits.

2023-09-01 00:49 UTC, DLLarson commented
All righty then... Here goes....

-Dale

2023-09-01 00:50 UTC, merged