Replace dibapi
CyberBoardPBEM/cbwindows pull request #123
Opened 2023-11-26 02:58 UTC by wsu-cb

Replace the Microsoft-copyrighted `DibAPI.*` code.  Because the replacement is based on wxWidgets's `wxImage`, which is always (at least) 24bpp, we might as well use 24bpp throughout CB.

Fix #121

2023-11-26 03:12 UTC, wsu-cb commented
Converted to draft due to build failure...

2023-11-26 19:38 UTC, DLLarson commented
Hi Bill,

Exciting stuff! I'll be digging into this over the next couple weekdays.

-Dale

2023-12-04 23:01 UTC, DLLarson commented
Hi Bill,

A progress note...

I'm about 80% done looking at the code but it'll take a few more days. I'm liking what I see. I also want to step through some of the code in the debugger as well.

-Dale

2023-12-10 18:38 UTC, DLLarson requested changes
Hi Bill,

Ok... I've *finally* finished reviewing the changes. I'll still be running the code under the debugger some to get a functional feel for the mods. Note that all this took extra time with the holidays upon us. I don't expect it'll get better before the month is out.

-Dale

2023-12-10 20:30 UTC, wsu-cb commented on GM/Gm.h
> +extern const wxDataFormat CF_TILEIMAGES;      // Dword count, dword small colorref, full Dib,
Could you be more specific about where?  I can't find a tab in this file.

2023-12-10 20:46 UTC, wsu-cb commented on GShr/Rotate.cpp
> +CDib CDib::Rotate(int angle, COLORREF crTrans) const
I saw that, but the function documentation https://docs.wxwidgets.org/3.2/classwx_image.html#a3532210633dae17f21e99d111b1ef0b2 suggests that it has two problems for our use case:
1.  It sets "uncovered" pixels to black instead of our transparent color.
2.  It requires an integer-valued rotation center point, which I'm not sure will work well for a tile with sides of even length.

Because of those issues, I didn't bother experimenting with the function.

2023-12-10 23:54 UTC, wsu-cb commented on GShr/CDib.cpp
> +    inline COLORREF RGB565_TO_24(uint16_t clr16)
Could you please check this function again?  I am reasonably sure this function will convert 0x1F to 0xFF.  Also, this is the function that is in v3.5-prerelease-2 GdiTools.h; I just moved it since it doesn't need to be "public" any more.

2023-12-10 23:58 UTC, wsu-cb commented on GShr/GdiTools.cpp
>  // specified position. If crTrans is specified, a masked merge is
Will be corrected in next push.

2023-12-11 19:52 UTC, DLLarson commented on GM/Gm.h
> +extern const wxDataFormat CF_TILEIMAGES;      // Dword count, dword small colorref, full Dib,
My mistake. I misinterpreted the highlighted "gap" as a tab like it is in my editor. It turns out that this is just showing the space diff.

![image](https://github.com/CyberBoardPBEM/cbwindows/assets/175455/1a9e7c5d-0388-4aab-a10f-e16b970f5b60)

2023-12-11 19:55 UTC, DLLarson commented on GShr/Rotate.cpp
> +CDib CDib::Rotate(int angle, COLORREF crTrans) const
Ok... Makes sense.

-Dale

2023-12-11 21:15 UTC, DLLarson commented on GShr/CDib.cpp
> +    inline COLORREF RGB565_TO_24(uint16_t clr16)
You are correct. I misinterpreted the code. It does properly upscale. My bad.

2023-12-11 21:22 UTC, DLLarson requested changes
I really sucked in this review. Zero for three on defects. Anyway, I'll merge when you get the fixed comment committed.

2023-12-12 15:02 UTC, DLLarson approved these changes
Good to go!

-Dale

2023-12-12 15:04 UTC, DLLarson commented
A squash merge may be the best approach for this. What's your take?

-Dale

2023-12-12 16:39 UTC, wsu-cb commented
> A squash merge may be the best approach for this. What's your take?
> 
> -Dale

This PR is pretty big as a single commit, but it is reasonably well-focused on changing the CDib internals.  I don't have a strong opinion.

2023-12-12 20:07 UTC, DLLarson commented
>but it is reasonably well-focused on changing the CDib internals.

Yep. This is why I'd rather squash in this instance. It's well focused. Otherwise a PR may be able to be semi-squashed (manually using interactive rebase) down to a couple cohesive commits. This time though I'm going with the full squash.

-Dale

2023-12-12 20:09 UTC, merged