convert to wxDialog part01
CyberBoardPBEM/cbwindows pull request #124
Opened 2023-12-25 05:08 UTC by wsu-cb

Convert several MFC-based dialog boxes to wx-based dialog boxes.

2023-12-28 15:54 UTC, DLLarson commented
The programs don't build for me using `build-all-configs.bat`. Do you see anything obvious in the attached build output?

[build-out-pr-124.txt](https://github.com/CyberBoardPBEM/cbwindows/files/13787832/build-out-pr-124.txt)
-Dale

2023-12-29 05:07 UTC, wsu-cb commented
I can only infer that a difference in versions between your STL and mine/Github's allowed Github and me to get away with not explicitly including <mutex>.

2023-12-29 16:46 UTC, DLLarson commented
> (The missing declarations are already required in the `master` branch. Did you upgrade MSVS since you last compiled `master`?)

Yes, I did "update" my MSVS (as I typically do when it says an update is available) but not to an entirely new version. The About box version is 17.8.3. VS is still called 2022.

Any ideas how to fix the situation?

-Dale

2023-12-29 20:41 UTC, wsu-cb commented
> Any ideas how to fix the situation?
> 

Did you see the additional commit https://github.com/CyberBoardPBEM/cbwindows/pull/124/commits/9c3704c09de9d9178defd43f6b6bebcf3de8de24?  I think that should work independent of compiler version.

2023-12-29 22:14 UTC, DLLarson commented
> Did you see the additional commit [9c3704c]

No I didn't. I'll go pull that down.

-Dale

2023-12-30 03:13 UTC, DLLarson commented
I pulled down the latest commits and verified the new commit was present. The build still breaks for some reason having to do with templates in Dld*.cpp files. See attached...

[build-all-20231229.txt](https://github.com/CyberBoardPBEM/cbwindows/files/13796957/build-all-20231229.txt)


-Dale

2024-01-01 03:11 UTC, wsu-cb commented
I updated my MSVS, reproduced the problem, and have now fixed it.

2024-01-01 17:56 UTC, DLLarson commented
It's building now!

One weird thing... When I used the batch file to build all the targets target `x64-Debug` had no executables in the runtime folder. When I simply ran the batch file again the runtime folder then contained the proper files. Not sure why it missed out the first run after checkout.

Ok... I'm continuing the review...

-Dale

2024-01-01 18:10 UTC, DLLarson commented
The menus are showing a strange shadow bitmaps....

![image](https://github.com/CyberBoardPBEM/cbwindows/assets/175455/96f4cd80-b2d6-4808-8221-d66f080feca3)

-Dale

2024-01-01 20:06 UTC, wsu-cb commented
> The menus are showing a strange shadow bitmaps....
> 

On my system, that is a gray alpha-blended shadow.  I don't intentionally generate the shadow; it seems to be automatic.

Is this something that goes away after a reboot?  Or maybe another High DPI issue?

2024-01-01 20:10 UTC, wsu-cb commented
> One weird thing... When I used the batch file to build all the targets target `x64-Debug` had no executables in the runtime folder. When I simply ran the batch file again the runtime folder then contained the proper files. Not sure why it missed out the first run after checkout.

I will put more `if errorlevel` checks in.

2024-01-01 22:06 UTC, DLLarson requested changes
I'm done. 

The plumbing for wxWidgets dialogs are an adjustment from the MFC patterns. The source code is getting to be more modern C++ with each PR. Nice to see. It also looks like the conversion of dialogs and resources are going to be a big part of the labors moving to wxWidgets.

I had a few questions in the review.

When we commit all this my vote would be to *not* squash in this case. The commits clearly reflect development steps so best not to lose that.

-Dale

2024-01-01 22:29 UTC, wsu-cb commented on GM/Gm.cpp
> +wxString test = wxString("hello, �") + "world\nline2\n";
It's the Euro currency symbol.  I have it in the code intentionally for testing non-ASCII.

2024-01-01 22:51 UTC, wsu-cb commented on GM/Gm.cpp
> +wxString test = wxString("hello, �") + "world\nline2\n";
(In CodePage 1252.)  The source code has some non-ASCII chars (the chevrons used internally), and at some point we will have to decide what to do about that since it's non-portable.

2024-01-01 23:10 UTC, wsu-cb commented on GM/CBDesign.fbp
This is the file format for wxFormBuilder.  It's the most convenient approximation (to my knowledge) to the Win32 Resource Editor for wx .xrc files, but doesn't use .xrc files directly.  I edit the .fbp in wxFormBuilder, and then export the .xrc for use at runtime.  I think it's desirable to keep it in SCM, at least until we find some better editor.

2024-01-02 02:24 UTC, wsu-cb commented on GM/DlgBrdp.cpp
CB 3.1 is allowing 3 digits after the decimal point also.  If you mean that the display shows `4.000` instead of `4`, then we could probably construct a `wxValidator` subclass that displays `4` while allowing the user to enter `4.123`, but it doesn't seem like a high priority to me.

2024-01-02 02:33 UTC, wsu-cb commented
> The plumbing for wxWidgets dialogs are an adjustment from the MFC patterns. The source code is getting to be more modern C++ with each PR. Nice to see. It also looks like the conversion of dialogs and resources are going to be a big part of the labors moving to wxWidgets.

The dialog conversions are going to be a lot of work, but I think they can be done in relatively small chunks.  My concern is that the work to replace the MFC document/view architecture will be very difficult to break up into manageable chunks.

> When we commit all this my vote would be to _not_ squash in this case. The commits clearly reflect development steps so best not to lose that.

Indeed, that was very intentional.

2024-01-03 15:24 UTC, DLLarson commented
> On my system, that is a gray alpha-blended shadow. I don't intentionally generate the shadow; it seems to be automatic.
> 
> Is this something that goes away after a reboot? Or maybe another High DPI issue?

Reboot didn't fix. However setting the windows display to 100% scaling yields what you see. When I scale to anything larger the weird artifacts appear. So it's definitely a High DPI issue.

We can leave this for now. Perhaps we can turn off the shadow in wxWidgets if High DPI is detected for now.

-Dale

2024-01-03 15:28 UTC, DLLarson commented on GM/DlgBrdp.cpp
Ok... I missed that I was using scaled decimal for those fields. 

>. If you mean that the display shows 4.000 instead of 4,

Perhaps best to keep the wider form since not having it confused me into thinking that the field wasn't fractional. The new form is more explicit.

-Dale

2024-01-03 15:31 UTC, DLLarson commented on GM/Gm.cpp
> +wxString test = wxString("hello, �") + "world\nline2\n";
>(In CodePage 1252.) The source code has some non-ASCII chars (the chevrons used internally), and at some point we will have to decide what to do about that since it's non-portable.

Thanks for the clarification. Indeed we'll need to do some unicode mapping of these. The chevron should definitely exist in Unicode.

2024-01-03 15:33 UTC, DLLarson commented
>My concern is that the work to replace the MFC document/view architecture will be very difficult to break up into manageable chunks.

Especially when we need to switch to wxWidgets GDI support.

-Dale

2024-01-03 15:35 UTC, DLLarson commented on GM/CBDesign.fbp
>I think it's desirable to keep it in SCM, at least until we find some better editor.

Understood.

-Dale

2024-01-03 17:01 UTC, DLLarson commented
> > One weird thing... When I used the batch file to build all the targets target `x64-Debug` had no executables in the runtime folder. When I simply ran the batch file again the runtime folder then contained the proper files. Not sure why it missed out the first run after checkout.
> 
> I will put more `if errorlevel` checks in.

It still breaks on the first run after a completely new checkout. Running again builds everything. Here's the failed run:

```


-- The CXX compiler identification is MSVC 19.38.33133.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.38.33130/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Deprecation Warning at deps/wxWidgets/CMakeLists.txt:10 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- The C compiler identification is MSVC 19.38.33133.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.38.33130/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of wchar_t
-- Check size of wchar_t - done
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - not found
-- Found Threads: TRUE
-- Performing Test HAVE_WINHTTP_H
-- Performing Test HAVE_WINHTTP_H - Success
-- Looking for d2d1.h
-- Looking for d2d1.h - found
-- Found OpenGL: opengl32
-- Looking for 4 include files stdlib.h, ..., float.h
-- Looking for 4 include files stdlib.h, ..., float.h - found
-- Performing Test HAVE_GCC_ATOMIC_BUILTINS
-- Performing Test HAVE_GCC_ATOMIC_BUILTINS - Failed
-- Looking for localtime_r
-- Looking for localtime_r - not found
-- Looking for gmtime_r
-- Looking for gmtime_r - not found
-- Performing Test wxSIZE_T_IS_NOT_UINT
-- Performing Test wxSIZE_T_IS_NOT_UINT - Success
-- Performing Test wxSIZE_T_IS_NOT_ULONG
-- Performing Test wxSIZE_T_IS_NOT_ULONG - Success
-- Performing Test wxWCHAR_T_IS_REAL_TYPE
-- Performing Test wxWCHAR_T_IS_REAL_TYPE - Success
-- Performing Test HAVE_PW_GECOS
-- Performing Test HAVE_PW_GECOS - Failed
-- Looking for ftime
-- Looking for ftime - not found
-- Looking for wcsftime
-- Looking for wcsftime - found
-- Looking for wprintf
-- Looking for wprintf - found
-- Looking for putws
-- Looking for putws - not found
-- Looking for fputws
-- Looking for fputws - found
-- Looking for vswprintf
-- Looking for vswprintf - found
-- Looking for vswscanf
-- Looking for vswscanf - found
-- Looking for wcsdup
-- Looking for wcsdup - found
-- Looking for wcsnlen
-- Looking for wcsnlen - found
-- Looking for wcscasecmp
-- Looking for wcscasecmp - not found
-- Looking for wcsncasecmp
-- Looking for wcsncasecmp - not found
-- Looking for wcsrctombs
-- Looking for wcsrctombs - not found
-- Looking for wcstoull
-- Looking for wcstoull - found
-- Looking for wcslen
-- Looking for wcslen - found
-- Looking for fsync
-- Looking for fsync - not found
-- Looking for snprintf
-- Looking for snprintf - found
-- Looking for vsnprintf
-- Looking for vsnprintf - not found
-- Looking for strnlen
-- Looking for strnlen - found
-- Looking for strtoull
-- Looking for strtoull - found
-- Looking for setpriority
-- Looking for setpriority - not found
-- Looking for gettimeofday
-- Looking for gettimeofday - not found
-- Looking for vsscanf
-- Looking for vsscanf - found
-- Looking for fcntl.h
-- Looking for fcntl.h - found
-- Looking for langinfo.h
-- Looking for langinfo.h - not found
-- Looking for sched.h
-- Looking for sched.h - not found
-- Looking for unistd.h
-- Looking for unistd.h - not found
-- Looking for wchar.h
-- Looking for wchar.h - found
-- Looking for wcstr.h
-- Looking for wcstr.h - not found
-- Performing Test wxTEST_TZ_timezone
-- Performing Test wxTEST_TZ_timezone - Failed
-- Performing Test wxTEST_TZ__timezone
-- Performing Test wxTEST_TZ__timezone - Success
-- Performing Test WX_GMTOFF_IN_TM
-- Performing Test WX_GMTOFF_IN_TM - Failed
-- Looking for dlopen
-- Looking for dlopen - not found
-- Looking for sys/epoll.h
-- Looking for sys/epoll.h - not found
-- Looking for sys/select.h
-- Looking for sys/select.h - not found
-- Looking for sys/inotify.h
-- Looking for sys/inotify.h - not found
-- Looking for sys/event.h
-- Looking for sys/event.h - not found
-- Looking for xlocale.h
-- Looking for xlocale.h - not found
-- Check size of locale_t
-- Check size of locale_t - failed
-- Check size of size_t
-- Check size of size_t - done
-- Check size of int
-- Check size of int - done
-- Check size of long
-- Check size of long - done
-- Check size of short
-- Check size of short - done
-- Check size of long long
-- Check size of long long - done
-- Check size of ssize_t
-- Check size of ssize_t - failed
-- Which libraries should wxWidgets use?
    wxUSE_REGEX:    builtin  (enable support for wxRegEx class)
    wxUSE_ZLIB:     builtin  (use zlib for LZW compression)
    wxUSE_EXPAT:    builtin  (use expat for XML parsing)
    wxUSE_LIBJPEG:  builtin  (use libjpeg (JPEG file format))
    wxUSE_LIBPNG:   builtin  (use libpng (PNG image format))
    wxUSE_LIBTIFF:  builtin  (use libtiff (TIFF file format))
    wxUSE_NANOSVG:  builtin  (use NanoSVG for rasterizing SVG)
    wxUSE_LIBLZMA:  OFF      (use liblzma for LZMA compression)

-- Configured wxWidgets 3.3.0 for Windows-10.0.19045
    Min OS Version required at runtime:                Windows 7 / Windows Server 2008 (x64 Edition)
    Which GUI toolkit should wxWidgets use?            msw
    Should wxWidgets be compiled into single library?  OFF
    Should wxWidgets be linked as a shared library?    OFF
    Which wxWidgets API compatibility should be used?  3.2
-- Configuring done (35.1s)
-- Generating done (0.3s)
-- Build files have been written to: D:/Dev/CBoard/G/cbwindows/out/build/x64-Debug

D:\Dev\CBoard\G\cbwindows>if errorlevel 1 goto fail_cmake

D:\Dev\CBoard\G\cbwindows>cmake --build out/build/x64-Debug
[153/913] Copy gmhelp.h
        1 file(s) copied.
[155/913] Copy gphelp.h
        1 file(s) copied.
[160/913] Building RC object GP\CMakeFiles\CBPlay.dir\Cbplay.rc.res
FAILED: GP/CMakeFiles/CBPlay.dir/Cbplay.rc.res
C:/PROGRA~1/CMake/bin/cmcldeps.exe RC D:\Dev\CBoard\G\cbwindows\GP\Cbplay.rc GP\CMakeFiles\CBPlay.dir\Cbplay.rc.res.d GP\CMakeFiles\CBPlay.dir\Cbplay.rc.res "Note: including file: " "C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.38.33130/bin/Hostx64/x64/cl.exe" C:\PROGRA~2\WI3CF2~1\10\bin\100220~1.0\x64\rc.exe -DGPLAY -DUNICODE -D_AFX_SECURE_NO_WARNINGS -D_ATL_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_WARNINGS -D_CRT_SECURE_NO_WARNINGS -D_DEBUG -D_UNICODE -D__WXMSW__ -I D:\Dev\CBoard\G\cbwindows\GP\. -I D:\Dev\CBoard\G\cbwindows\GP\..\GShr -I "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\atlmfc\src\mfc" -I D:\Dev\CBoard\G\cbwindows\out\build\x64-Debug\deps\wxWidgets\lib\vc_x64_lib\mswud -I D:\Dev\CBoard\G\cbwindows\deps\wxWidgets\include -DWIN32 -D_DEBUG /fo GP\CMakeFiles\CBPlay.dir\Cbplay.rc.res D:\Dev\CBoard\G\cbwindows\GP\Cbplay.rc
D:\Dev\CBoard\G\cbwindows\GP\Cbplay.rc(3): fatal error C1083: Cannot open include file: 'resource.h': No such file or directory
[172/913] Building CXX object GP\CMakeFiles\CBPlay.dir [...]

2024-01-04 01:26 UTC, wsu-cb commented
> Reboot didn't fix. However setting the windows display to 100% scaling yields what you see. When I scale to anything larger the weird artifacts appear. So it's definitely a High DPI issue.
> 
> I also noticed that not all menus have the artifacts. If I right-click a board view the menu shadow looks fine. If I right-click a palette style window the artifacts are there.
> 

Weird.

> We can leave this for now. Perhaps we can turn off the shadow in wxWidgets if High DPI is detected for now.
> 

Unfortunately, I'm not explicitly enabling shadows, and even CB 3.1 displays shadows.  I don't know how easy it will be to get rid of them.

2024-01-04 01:43 UTC, wsu-cb commented
> It still breaks on the first run after a completely new checkout. Running again builds everything. Here's the failed run:
> 

...

> [160/913] Building RC object GP\CMakeFiles\CBPlay.dir\Cbplay.rc.res
> FAILED: GP/CMakeFiles/CBPlay.dir/Cbplay.rc.res
> C:/PROGRA~1/CMake/bin/cmcldeps.exe RC D:\Dev\CBoard\G\cbwindows\GP\Cbplay.rc GP\CMakeFiles\CBPlay.dir\Cbplay.rc.res.d GP\CMakeFiles\CBPlay.dir\Cbplay.rc.res "Note: including file: " "C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.38.33130/bin/Hostx64/x64/cl.exe" C:\PROGRA~2\WI3CF2~1\10\bin\100220~1.0\x64\rc.exe -DGPLAY -DUNICODE -D_AFX_SECURE_NO_WARNINGS -D_ATL_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_WARNINGS -D_CRT_SECURE_NO_WARNINGS -D_DEBUG -D_UNICODE -D__WXMSW__ -I D:\Dev\CBoard\G\cbwindows\GP\. -I D:\Dev\CBoard\G\cbwindows\GP\..\GShr -I "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\atlmfc\src\mfc" -I D:\Dev\CBoard\G\cbwindows\out\build\x64-Debug\deps\wxWidgets\lib\vc_x64_lib\mswud -I D:\Dev\CBoard\G\cbwindows\deps\wxWidgets\include -DWIN32 -D_DEBUG /fo GP\CMakeFiles\CBPlay.dir\Cbplay.rc.res D:\Dev\CBoard\G\cbwindows\GP\Cbplay.rc
> D:\Dev\CBoard\G\cbwindows\GP\Cbplay.rc(3): fatal error C1083: Cannot open include file: 'resource.h': No such file or directory

That's weird.  The `resource.h` files aren't generated, so I don't understand how the system can say they don't exist, at least not when they do exist on a second try.  And why does it only happen in the .bat file?  I could force a second try if the first fails in the .bat file, but it's certainly an ugly kludge.

2024-01-13 16:55 UTC, DLLarson commented
>I could force a second try if the first fails in the .bat file, but it's certainly an ugly kludge.

Well I can't see the problem either. For now we could just leave it or do the check and rerun (if it even works since we can't find the cause). 

-Dale

2024-01-13 16:58 UTC, DLLarson commented
>Unfortunately, I'm not explicitly enabling shadows, and even CB 3.1 displays shadows. I don't know how easy it will be to get rid of them.

Well we can kick this can down the road a bit since it doesn't affect functionality. I've been trying to locate where this takes place in the underlying MSW layer of wxWidgets but haven't found it yet. We shouldn't hold this work on account of this artifact.

2024-01-13 17:01 UTC, DLLarson approved these changes

2024-01-13 17:01 UTC, DLLarson commented
I'm ready to merge if you are.

-Dale

2024-01-13 18:25 UTC, DLLarson approved these changes
I guess it wants me to approve it again...

2024-01-13 18:29 UTC, DLLarson commented
Here's some info on High DPI support built into wxWidgets...

https://docs.wxwidgets.org/3.2/overview_high_dpi.html

It looks like we need to include a predefined .rc file for Windows to ensure the manifest has the proper High DPI settings:

```
The behaviour of the application when running on a high-DPI display depends on the values in
its [manifest](https://docs.microsoft.com/en-us/windows/win32/sbscs/application-manifests). 
You may either use your own manifest, in which case you need to define the dpiAware (for 
compatibility with older OS versions) and dpiAwareness (for proper per-monitor DPI support) in 
it, or simply include wx/msw/wx.rc from your resource file to use the manifest provided by 
wxWidgets and predefine wxUSE_DPI_AWARE_MANIFEST to opt-in into [high DPI support]
(https://docs.microsoft.com/en-us/windows/win32/hidpi/high-dpi-desktop-application-
development-on-windows): define it as 1 for minimal DPI awareness and 2 for full, per-monitor 
DPI awareness supported by Windows 10 version 1703 or later.
```

-Dale

2024-01-13 23:03 UTC, wsu-cb commented
> > I could force a second try if the first fails in the .bat file, but it's certainly an ugly kludge.
> 
> Well I can't see the problem either. For now we could just leave it or do the check and rerun (if it even works since we can't find the cause).
> 

I have been unable to reproduce the build failure on two different machines, but I have pushed a retry-on-failure despite it being untested.

2024-01-13 23:08 UTC, wsu-cb commented
> I'm ready to merge if you are.
> 

Yes, please.

2024-01-14 14:55 UTC, merged

2024-01-14 17:33 UTC, DLLarson commented
Final note on the batch file build... I just ran a batch file build of a clean `master` checkout containing the merged PR and associated submodules and everything worked.

-Dale