be more explicit about nature of ObjectID
CyberBoardPBEM/cbwindows pull request #27
Opened 2020-10-17 05:08 UTC by wsu-cb

I made some changes to clarify how ObjectID works (or at least how I think it works).  Could you review this and see if this looks correct to you?  I would like to do similar work for other "generic integer" types (PieceID, MarkID, GameElement) as well.  This is preparation for moving the 16 bit identifiers to 32 bit since I hope this will make it easier to understand how the identifiers currently behave.

2020-10-18 14:51 UTC, DLLarson requested changes
I like the overall approach. More modern. I hope we'll be safe using C++11 features from here out. I think we are (after all it was nine years ago since adopted!)

I added one requested change having to do with commenting the new class.

-Dale

2020-10-18 14:51 UTC, DLLarson commented on GShr/DrawObj.h
After our email discussions I think it would be good to summarize the reason for ObjectID's now that they are more explicit. Something about providing unique ID's in a manner that can be performed in a distributed manner that attempts to avoid ID collisions. At a higher level they are used to manage the maintenance of objects that pop into existence and then later can be destroyed in a distributed manner as well. Current and possible uses are creating markers, lines (used for plotting moves), grease pencil for freehand annotation. attaching disposible multimedia clips, etc...

2020-10-18 14:54 UTC, DLLarson commented on GShr/DrawObj.h
I ran into an operational issue. If I drag some markers onto a board. I can't delete them when selected.

Also, when I do a Ctrl drag of a marker onto the board it is suppose to prompt for a number of items to create but it asserts.

-Dale

2020-10-20 02:56 UTC, wsu-cb commented on GShr/DrawObj.h
I just tried the POG test, and was able to delete markers.  Could you please double-check that you were actually trying to delete markers, not pieces?  I notice that the POG test has PIECES that are in a group named "Control Markers".

2020-10-20 14:09 UTC, DLLarson commented on GShr/DrawObj.h
OMG!...

Egg on my face. I "bought" the idea that those pieces were markers because they said they were!

Sorry about that. My bad and all that.

Ummmm... Never mind...

-Dale

2020-10-21 14:39 UTC, DLLarson approved these changes
Looks good!

-Dale

2020-10-21 14:39 UTC, merged

2020-10-22 02:05 UTC, wsu-cb commented
I am planning to do more of this kind of work before tackling the actual conversion to 32bit ids.  Do I need to create a new branch for continuing on, or can I continue using this branch?  Assuming I can use this branch, can I continue to use this pull request, or do I need a new pull request now that this one has been closed?

2020-10-22 02:12 UTC, DLLarson commented
>Do I need to create a new branch for continuing on, or can I continue using this branch?

I think as a matter of good practice you should use a new branch with a descriptive name for any new work. At times you may have many so called "topic branches" in play. Best to retire the completed ones.

Note that this is not a rule. Certainly GIT doesn't require it.

-Dale

2020-10-22 02:28 UTC, wsu-cb commented
I had planned to work on clarifying the behavior of all the "simple integer type" identifiers, and similarly with things like CGrafixListBox::m_pItemMap, in this branch, but I can certainly use new branches for each identifier type.  However, I think the branches will have order-of-merge dependencies because a lot of files use more than one of these types.  To me, that suggests this should be a single branch rather than a bunch of branches.

2020-10-22 02:53 UTC, DLLarson commented
It's true that topic branches can go stale but that's what the `git rebase` command is for.

For me the ability to jump around in my work was essential (back in my working days that is) so this happened a lot. Some branches were long term projects, some where quick fixes, etc... 

Rebase straightens things out quite nicely. It's a very powerful command. `gitk --all` is handy to get a feel for the commits you are behind.

-Dale