Type safety for TileID/MarkID/PieceID (plus some other changes as a consequence)
CyberBoardPBEM/cbwindows pull request #36
Opened 2020-12-20 06:13 UTC by wsu-cb

This is a big changeset to review, but I didn't think the intermediate stages would much sense before the final result.

The original code uses typedef unsigned short TileID/MarkID/PieceID.  However, this means TileID/MarkID/PieceID are just additional names for unsigned short, and thus assigning a MarkID to a PieceID is permitted by the compiler.  I have changed this by making a template class for the IDs, and each ID type is given a different template parameter value, so the compiler views them as separate types and refuses to allow mixing the types.  However, this does require changing a lot of code that was written based on the IDs being unsigned short, which is part of why this changeset is so large.

Another reason the changeset is so large is that I discovered some repetitive code to handle storing growable arrays using GlobalAlloc instead of regular C++ heap.  I replaced that code with another template class.  I admit it is possible that should have been a separate changeset, but those arrays were indexed by the ID types, so I already needed to rewrite the code some to handle that change, and I think it was less work to replace the repetitive code with a template rather than fix each repetition separately.

Yet another issue is that std::vector and, following that model, the new GlobalAlloc growable array use size_t as an index, but most of MFC and current CyberBoard code uses int as its index type.  I actually think size_t makes more sense, so I didn't create an int-based std::vector replacement.  However, that means I was doing a lot of casting back and forth between size_t and int, so I added a template function similar to dynamic_cast<> that will throw if the conversion does not preserve the value across the conversion, and use it frequently.  If all of that casting bothers you, I think I could redo this patch using an int-based replacement for std::vector and the new GlobalAlloc growable array.  However, even doing that would require changing the existing code that uses int to intptr_t in the long run when we convert to 64bit code.  As such, I would rather use size_t.

2020-12-20 15:33 UTC, DLLarson reviewed
Hi Bill,

Wow.... There is a lot here! Plus many commits.

It will take me some time to go through this.

In general, I like the switch to STL collections and type safety (as discussed before.) I wouldn't mind seeing that program-wide as it enhances portability.

I'm going to have to dig around to understand the GlobalAlloc stuff usage. There is really no need for this in most (or any?) of the code unless it's to satisfy a specific requirement of a Win32 Api call.

This PR is a long stack of commits that probably should be rebased down to a single (or a couple) overarching commit topics that capture the overall intent of the PR. It's best to hide all the sausage making in the mainline code. I generally commit often and then, before submitting the change, I rebase it down to a single commit using interactive rebasing.

-Dale

2020-12-20 15:33 UTC, DLLarson commented on GShr/CyberBoard.h
> +#ifndef _CYBERBOARD_H
This file needs the standard MIT copyright license comment block like the other files.
Put your name in the copyright as you're the author.

-Dale

2020-12-20 16:52 UTC, wsu-cb commented
> In general, I like the switch to STL collections and type safety (as discussed before.) I wouldn't mind seeing that program-wide as it enhances portability.
> 

Since I was working on the multi-platform CB project, I obviously prefer to use STL over MFC when possible, but my immediate goal is the 32bit ID project, so I just convert to STL when it makes my current work easier.  The type safety is also important to me as a waypoint on the path to 32bit IDs.

> I'm going to have to dig around to understand the GlobalAlloc stuff usage. There is really no need for this in most (or any?) of the code unless it's to satisfy a specific requirement of a Win32 Api call.
> 

I wondered why some of the code was using GlobalAlloc, but that is how the code is written in the original commit (https://github.com/CyberBoardPBEM/cbwindows/blame/4f4206c634e11ff79174e40f47b21e1b8da76d61/GShr/TileMgr.cpp#L261), so I just maintained that behavior.  I will experiment with replacing the GlobalAlloc with standard memory allocation routines, and, assuming that works, will include that in the "clean" PR.

> This PR is a long stack of commits that probably should be rebased down to a single (or a couple) overarching commit topics that capture the overall intent of the PR. It's best to hide all the sausage making in the mainline code. I generally commit often and then, before submitting the change, I rebase it down to a single commit using interactive rebasing.
> 
> -Dale

OK, I will work on a clean PR.  Should that be a new branch (type-safety-ids-rebase), or should I rename the current branch (type-safety-ids-v1) and then create a new branch named type-safety-ids?

2020-12-20 18:49 UTC, DLLarson commented
>Should that be a new branch (type-safety-ids-rebase), or should I rename the current branch (type-safety-ids-v1) and then create a new branch named type-safety-ids?

A matter of personal preference. I would just create a new branch to save the current commit set (just in case) like so:  on the current working branch just use the command `git checkout -b type-safety-ids-v1` which should create and switch to the new (really the existing old) branch. Now just re-checkout the original branch and interactively rebase that. 

I try to squash related things together (perhaps reordering some commits in rebase interactive mode) into single commits. Rinse and repeat to get something you like and force push that up to replace the preview PR.

That's just how I'd do it to avoid creating new unnecessary PR's in GitHub.

-Dale

2020-12-20 19:05 UTC, wsu-cb commented
> > Should that be a new branch (type-safety-ids-rebase), or should I rename the current branch (type-safety-ids-v1) and then create a new branch named type-safety-ids?
> 
> A matter of personal preference. I would just create a new branch to save the current commit set (just in case) like so: on the current working branch just use the command `git checkout -b type-safety-ids-v1` which should create and switch to the new (really the existing old) branch. Now just re-checkout the original branch and interactively rebase that.
> 
> I try to squash related things together (perhaps reordering some commits in rebase interactive mode) into single commits. Rinse and repeat to get something you like and force push that up to replace the preview PR.
> 
> That's just how I'd do it to avoid creating new unnecessary PR's in GitHub.
> 
> -Dale

I suspect that I would get a clearer history by working in a new branch than trying to rebase the current one.  However, I think I have an idea:  If I create the new "clean" branch and build up the "pretty" history in it, and then "git reset master" the current branch, I could fast-forward merge the new branch into the current branch, and then force push the current branch.  That would still result in replacing the current PR rather than creating a new one, right?

2020-12-21 15:39 UTC, DLLarson commented
Hi Bill,

>I suspect that I would get a clearer history by working in a new branch than trying to rebase the current one.

I don't see how. Interactive rebase is super simple. You get a list of commits in a text file listed from oldest to latest. You can mark commits as pick (keeps the commit as it), squash (combine with next adjacent commit), etc...

Here's the `git rebase -i master` command text file you would be presented with to edit for the PR 36 checkout:

```
pick 96e712e provide explicit Invalid<> values for uintptr_t and size_t
pick 5fcf534 increase type-safety of CGmBoxHint
pick a87978f make TileID a struct for type-safety
pick 53095e3 make compatible with the drag-and-drop changes
pick 08252cc share code for TileID/MarkID/PieceID using templates
pick 1e18eed replace CPtrArray with strictly typed std::vector
pick bf249a2 improve type-safety of WM_OVERRIDE_SELECTED_ITEM parameter
pick 3d4cfd1 std::vector uses size_t as index type, not int
pick bb6400d drop 'Tile' from name since it might actually be Mark or Piece
pick 97dea02 allow value-preserved integral value to be converted to XxxxID
pick 8351825 some preparation for 32bit id values
pick 64baf06 change some UINT to size_t for portability
pick 219c557 for type safety, reimplement MarkID as an XxxxID
pick 589104d generalize ResizeTable to support more ELEMENT types and skip unnecessary inits
pick 4c96fbb provide helper variable template
pick a1911ca replace std::string::npos with Invalid_v<size_t>
pick 4df72e5 replace some uses of unique_ptr<T> with T
pick 9428fe5 separate overloaded members into a union to allow more precise types
pick b0eb490 treat Resize(0) as Clear()
pick 94748cb reimplement PieceID as XxxxID
pick c08ec6b minor clean up
pick 619d49f more conversions of pointers to references
pick 61d7807 improve type safety of CGrafixListBox
pick a8f04e2 revert member variable names to reduce diffs relative to master

# Rebase 51b44d2..a8f04e2 onto a8f04e2 (24 commands)
#
# Commands:
# p, pick <commit> = use commit
# r, reword <commit> = use commit, but edit the commit message
# e, edit <commit> = use commit, but stop for amending
# s, squash <commit> = use commit, but meld into previous commit
# f, fixup <commit> = like "squash", but discard this commit's log message
# x, exec <command> = run command (the rest of the line) using shell
# b, break = stop here (continue rebase later with 'git rebase --continue')
# d, drop <commit> = remove commit
# l, label <label> = label current HEAD with a name
# t, reset <label> = reset HEAD to a label
# m, merge [-C <commit> | -c <commit>] <label> [# <oneline>]
# .       create a merge commit using the original merge commit's
# .       message (or the oneline, if no original merge commit was
# .       specified). Use -c <commit> to reword the commit message.
#
# These lines can be re-ordered; they are executed from top to bottom.
#
# If you remove a line here THAT COMMIT WILL BE LOST.
#
# However, if you remove everything, the rebase will be aborted.
#
```
Basically you edit the commit lines (comment lines are ignored) to what do what you want to happen and when you exit the editor the rebase continues automatically. I most commonly use `squash` and `pick`. You can also rearrange the order of commits but I usually don't do that unless it's down to a couple commits or they are very close to the commit I want to squash with. Note that you'll also be prompted at times to finalize any comments for squashed commits.

Interactive rebase is one of GIT's most powerful and useful features. 

Once you're done you just do a force push up on the topic branch and GitHub should be good to go.

As for your suggested approach I'm not sure how you're actually cleaning the commits up since that's what interactive rebase is all about. Doing it manually seems risky. As far as the "fast forward" onto `master` goes, this is what happens when you do interactive rebase as well. That's one of the goals of rebasing--to avoid 'merge' commits.

Anyway.... Just choose what you're most comfortable and give it a go. But I hope I clarified how I tend to go about these things. 

Note that you can always check out a test copy of your branch and experiment with it without risking what you already have.

-Dale

2020-12-28 15:34 UTC, DLLarson reviewed
>Another reason the changeset is so large is that I discovered some repetitive code to handle storing growable arrays using GlobalAlloc instead of regular C++ heap.

I lost on this after looking at the `CyberBoard.h` header code. Why is this needed again? What's wrong with the C++ heap management? It's been tuned for years and is probably as efficient as can be without looking toward edge cases. What am I missing here?

-Dale

2020-12-28 15:34 UTC, DLLarson commented on GShr/CyberBoard.h
> +    explicit XxxxID(T i) : XxxxID(value_preserving_cast<uint32_t>(i)) { static_assert(std::is_integral_v<T>, "id must be an integer"); }
Shouldn't the 'id' be an unsigned value?

2020-12-28 16:36 UTC, wsu-cb commented
> > Another reason the changeset is so large is that I discovered some repetitive code to handle storing growable arrays using GlobalAlloc instead of regular C++ heap.
> 
> I'm lost on this after looking at the `CyberBoard.h` header code. Why is this needed again? What's wrong with the C++ heap management? It's been tuned by compiler runtime implementers for years and is probably as efficient as can be without looking at oddball edge cases. What am I missing here?
> 
> -Dale

As I said in https://github.com/CyberBoardPBEM/cbwindows/pull/36#issuecomment-748632095, I don't know why GlobalAlloc is used, but the original code used it, so I followed that pattern.  Since then, I have done some brief experiments, and don't see a problem with malloc/realloc/free, so I will use those until I see a problem.  I am using C heap malloc/realloc/free because the original code does reallocate, and C++ heap new/delete don't have a realloc (or at least I'm not aware of one).

2020-12-28 17:20 UTC, wsu-cb commented on GShr/CyberBoard.h
> +// KLUDGE:  bool to work around possibility that uintptr_t is different from size_t
> For this inspection I'm starting with `Cyberboard.h` file as I think understanding this header will make the reset of the review work easier to grok. That said...
> 

Definitely.

> How does this kluge work? In fact I'm lost as to what is happening in this block of templates. I'm no expert at templates but I do have some working knowledge of them as I suspect most people do. It would be helpful if there some narrative to educate how this code is working.
> 

Let's see if this clarifies the issue:
In my updated code, size_t is used all over because that's the index type for std::vector. 
 (I am too lazy to use std::vector<T>::size_type.)  The original code frequently used -1 to indicate "no-value" for an index parameter.  I wanted to use std::numeric_limits<size_t>::max() for this purpose, but that was too long, so I declared a constexpr Invalid_size_t or something like that.  However, I found a spot in the code where uintptr_t seems more appropriate.  I could have declared Invalid_uintptr_t, but I felt like a situation like this cried out for using template Invalid<T>.  The problem is that both size_t and uintptr_t are specified by the compiler as typedefs to the same C++ fundamental type.  That means that attempting to explicitly instantiate Invalid<size_t> and Invalid<uintptr_t> is viewed by the compiler as conflicting instantiations.  To get around this problem, I added a second default template argument to Invalid<>, and have the default value be different for size_t and uintptr_t.  By making that second argument different, the compiler sees them as separate instantiations, and is satisfied.  If you look at the 

Admittedly, this does have some drawbacks.
1)  If the developer explicitly provides a value for the second argument, and it doesn't match the default value, there will be trouble.  I think that will be just a compiler error, so I don't think this is a serious problem.
2)  If I find a use for another Invalid<T> where T is the same fundamental type as size_t, this scheme will break down, and I will have to think of a more complicated disambiguation technique.
3)  I haven't tested this on a compiler where size_t and uintptr_t are fundamentally different types.  I'm not sure if this exact code will work in that case or not, but I think the code can be tweaked to handle both cases if we actually have a way to run the experiment conveniently.
4)  For this compiler where size_t and uintptr_t are actually the same, Invalid<size_t> and Invalid<uintptr_t> both map to the same instantiation, and have the same value.  However, that's not really a problem since the fundamental types are the same, so value = std::numeric_limits<T>::max() would end up using the same type fundamental U and hence have the same value even if the compiler somehow allowed different Invalid<> instantiations to be used.

> A blank blank line (a nit I know!) between each template definition would help some so I don't see just a block of templates munged together. Templates are difficult enough to mentally parse even if well formatted.

I will put them in the "pretty" version I am currently working on.

2020-12-28 17:58 UTC, wsu-cb commented on GShr/CyberBoard.h
> +    explicit XxxxID(T i) : XxxxID(value_preserving_cast<uint32_t>(i)) { static_assert(std::is_integral_v<T>, "id must be an integer"); }
If you are referring to the type restriction in template<typename T> explicit XxxxID(T i), then we could restrict T to be unsigned.  However, literal 0xFFFF and 0 are both type int, so TileID(0xFFFF) and TileID(0) would both illegal in that case.  We would have to use TileID(0xFFFFu) and TileID(0u).  Is requiring T be unsigned still something you want to do?

2020-12-28 22:27 UTC, DLLarson requested changes
Whew! That was a big 'un! 

Most was just substitution but still it hits a lot of code.

It's great to see some introduction of const-ness in the code. That's usually tough to do with old code. Lots of ripple effects but can provide real benefits for code safety.

I built and cursory tested the programs with a couple GameBox and Game files and all seems well. 

Well done!

-Dale

2020-12-28 22:27 UTC, DLLarson commented on GShr/TileMgr.cpp
> +    ASSERT(m_pTileTbl.Valid(tid));
Much better to have a call. It says what's going on explicitly. Nice!

2020-12-28 22:27 UTC, DLLarson commented on GShr/CyberBoard.h
> +    explicit XxxxID(T i) : XxxxID(value_preserving_cast<uint32_t>(i)) { static_assert(std::is_integral_v<T>, "id must be an integer"); }
Nope.

2020-12-29 07:05 UTC, wsu-cb commented on GShr/LBoxProj.h
> +    int AddItem(int nGroupCode, LPCSTR pszText, size_t nSourceCode = Invalid_v<size_t>);
I'm not sure what specifically you are asking about here, but let's see if any of this answers your question:

`Invalid_v<size_t>` is a convenience helper for `Invalid<size_t>::value`, loosely following the STL convention (e.g., `std::is_same<T, U>::value` and `std::is_same_v<T, U>`).

I'm using `Invalid<T>::value` as a more generic "no-value" value since I can make its type be `T`.  In the `size_t` case, I use an explicit template specialization to set its value to `std::numeric_limits<size_t>::max()` since an index of that value won't be reached without running into memory problems first.  (And, it actually will probably be the same bit pattern as -1, but that's probably because you picked -1 for much the same reason.)

2020-12-29 07:20 UTC, wsu-cb commented on GShr/Tile.h
> +    std::vector<CTileSet> m_TSetTbl;
Yes, I think there is a cost to using full objects.  In my "pretty" version, I have already started adding move constructors and move assignments and removing copy constructors/assignments from some of these objects.

However, I probably won't be posting the pretty version for a while.  It's an even bigger job than I was expecting because I have found some additional issues to address while working on it.  Move operations is one of these.  Spotting all of the int/size_t type changes is another.  I have been running some experiments on how to get the compiler to help me catch those.

2020-12-29 07:31 UTC, wsu-cb commented on GShr/TileSet.cpp
> +        ar << m_tidTbl;
The previous code had `m_tidTbl.Serialize(ar)` at the end of `CTileSet::Serialize()`.  (See the TileSet.cpp diff for commit a87978f.)

2020-12-30 16:34 UTC, DLLarson commented on GShr/LBoxProj.h
> +    int AddItem(int nGroupCode, LPCSTR pszText, size_t nSourceCode = Invalid_v<size_t>);
>I use an explicit template specialization to set its value to `std::numeric_limits<size_t>::max()`...

Ahhh... I missed that part. I was having trouble figuring out were the actual numeric value came from. Now it makes sense.

Again... it wouldn't hurt putting the above explanation as a comment in the code. 

Thanks!
-Dale

2020-12-30 16:39 UTC, DLLarson commented
>I don't know why GlobalAlloc is used, but the original code used it, so I followed that pattern.

It hails back to the original win16 version of CB where you had LocalAlloc and GloblalAlloc which actually had a real purpose with dealing with NEAR and FAR pointers and the like. Once in place, if there isn't a reason to change the code, it just hangs around. Time to ditch it where we can.

-Dale

2020-12-30 16:53 UTC, DLLarson commented on GShr/Tile.h
> +    std::vector<CTileSet> m_TSetTbl;
> I have already started adding move constructors and move assignments and removing copy constructors/assignments from some of these objects.

Ok. Makes sense. The move semantics stuff, if I recall correctly, is somewhat new in the C++ specs. Probably started in C++11.

2020-12-30 16:56 UTC, DLLarson commented on GShr/TileSet.cpp
> +        ar << m_tidTbl;
Ahhhh... Ok. I see it now. Thanks!

-Dale

2021-03-06 21:10 UTC, wsu-cb commented
In https://github.com/CyberBoardPBEM/cbwindows/pull/36#discussion_r549446644, there is a request to postpone further updates until after you finish reviewing the current set, and an indication that you expected to be done pretty quickly.  However, I'm not sure whether https://github.com/CyberBoardPBEM/cbwindows/pull/36#pullrequestreview-559234720 was the indication that you are ready to review a newer, hopefully cleaner, version of this code.

2021-03-06 22:32 UTC, DLLarson commented
>there is a request to postpone further updates until after you finish reviewing the current set,

Oh... I've been done for a long time now. I just thought you got busy with some other parts of your life.

What's weird is I thought I indicated the review is done but I'm not sure now where that happened.

Hmmmmmm.

-Dale

2021-04-01 01:39 UTC, wsu-cb commented
I have pushed a cleaned-up version of this PR for review.  From comments above, I suspect some additional squashing of commits will be suggested, but I will wait for specific suggestions.

2021-04-01 14:09 UTC, DLLarson commented
Hi Bill,

Ok.... I'll pull it down and start looking at them.

-Dale

2021-04-02 22:47 UTC, wsu-cb commented
> Hi Bill,
> 
> Ok.... I'll pull it down and start looking at them.
> 
> -Dale

Should I rebase this onto the new master (1a2999ea) and re-force-push it now, or postpone rebasing until after you review this version?

2021-04-02 23:02 UTC, DLLarson commented
Hi Bill,

Wait a bit longer. I'm almost done, then we can figure that out.

-Dale

2021-04-03 15:28 UTC, DLLarson commented
WHEW!!!! Ok... 

I'm done looking the code over. Needless to say there is lots there although most are boilerplate changes reacting to underlying redefinitions. It's real easy to get code inspection fatigue with something this size. Fortunately GitHub was very smart about what actually changed between the two commit sets. A very impressive feature.

Looking at the stack of commits in the PR, the changes appear to embody the single goal of improving type definitions in support of safely expanding those definitions later to support larger sets of various game objects. Given this is true, I would say it's best to collapse all these commits down to a single commit that describes this overall goal. I would collect the individual comment messages into comment for the resulting uber-commit (so to speak.) This way the whole commit can be reverted and/or reapplied as a unit. Any bugs found later can be added afterward.

After the PR collapsing rebase you can then rebase new PR commit against the current master branch to account for its changes. Then we'll absorb it onto the master branch.

A tip-of-my-hat to the amount of work you took on here. Impressive! Hopefully future efforts will be more bite sized after this. :)

-Dale

2021-04-03 18:38 UTC, wsu-cb commented
> Looking at the stack of commits in the PR, the changes appear to embody the single goal of improving type definitions in support of safely expanding those definitions later to support larger sets of various game objects. Given this is true, I would say it's best to collapse all these commits down to a single commit that describes this overall goal. I would collect the individual comment messages into comment for the resulting uber-commit (so to speak.) This way the whole commit can be reverted and/or reapplied as a unit. Any bugs found later can be added afterward.
> 
> A tip-of-my-hat to the amount of work you took on here. Impressive! Hopefully future efforts will be more bite sized after this. :)
> 
> -Dale

Thank you for the kind words.

Yes, this PR is mostly about improving type-safety in preparation for making actual functional changes in the future.  (Using STL is good for portability as well.)  However, there is still more type-safety work to be done.  (I am currently working on replacing CPtrList.)

Since you are talking about squashing these commits into a single commit, would it make sense for me to post PRs more frequently to make them easier to review, but to keep the PR in this type-safety branch?  Then we can squash this whole branch into a single commit and rebase it into master when I am done with type-safety work.

2021-04-03 18:47 UTC, DLLarson commented
>Since you are talking about squashing these commits into a single commit, would it make sense for me to post PRs more frequently to make them easier to review, but to keep the PR in this type-safety branch?

If this PR's commit allows the program, when built, to function as before I would prefer we finish this one off and put it in master. Then open a new PR to deal with the next cohesive stage in the work--even if it's within the same category of improvements. 

It's best not to make this one bigger. Just use it as the essential foundation for moving forward.

-Dale

2021-04-03 19:11 UTC, wsu-cb commented
Yes, this should be a working set of commits.

I will squash this, rebase it to master, and force-push it again.

2021-04-03 21:02 UTC, DLLarson approved these changes
Looks good!

I also cursory tested loading several versions of CB files and appears to be well.

I'll merge to master.


-Dale

2021-04-03 21:03 UTC, merged