Propconst+notnull+ptrlist
CyberBoardPBEM/cbwindows pull request #52
Opened 2021-06-27 04:01 UTC by wsu-cb

Here's some more type safety work.

1)  http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2015/n4388.html explains an often-undesirable characteristic of the C/C++ const type qualifier, and proposes a std::experimental::propagate_const<> template to provide a way to get around this.  However, this is not widely available, so I add a CB::propagate_const<> template to approximate the proposed standard, and then make use of it.

2)  In many cases, pointers are expected not to be null.  Add a CB::not_null<> template that can perform this checking automatically, and assert/throw if this assumption is violated.  Then make use of CB::not_null.

3)  Replace uses of MFC CPtrList (which contains void*) with more narrowly typed uses of std:;list<>.

2021-06-27 13:58 UTC, DLLarson commented
You've been busy! :)

This one--like the earlier large PR--will take a few days to get through.

-Dale

2021-06-28 13:40 UTC, DLLarson approved these changes

2021-06-28 13:52 UTC, DLLarson commented
At first I thought I'd try a different tact of inspecting the individual commits but it seems like when I OK the commit it applies to the full PR. This seems confusing. I'll keep doing this but not mark the commits as inspected until I the very end when I'll do it in aggregate.

-Dale

2021-06-28 14:00 UTC, DLLarson commented on GShr/CyberBoard.h
I'm assuming the plan is to remove this code when MSVC adopts the proposal?

2021-06-28 14:06 UTC, DLLarson commented on GShr/CyberBoard.h
> +
Inconveniently verbose indeed!

2021-06-28 14:08 UTC, DLLarson commented on GShr/CyberBoard.h
> +/* TODO:  The checks could be removed to improve release
Why trust when you don't have to? I say keep the test.

2021-06-28 14:29 UTC, DLLarson commented on GShr/DrawObj.h
> +/* WARNING:  Ownership of objects in CDrawList is hard to
Interesting!...

I suppose this should be attended to at some point. Thanks for adding the note.

2021-06-29 00:24 UTC, wsu-cb commented on GShr/CyberBoard.h
Yes.

2021-06-29 00:36 UTC, wsu-cb commented
> At first I thought I'd try a different tact of inspecting the individual commits but it seems like when I OK the commit it applies to the full PR. This seems confusing. I'll keep doing this but not mark the commits as inspected until I the very end when I'll do it in aggregate.
> 
> -Dale

Should I wait to push updates to address your comments (e.g., const CPalette*, thorough self-checking) until after you have finished reviewing the initial PR?

2021-06-29 01:53 UTC, DLLarson commented
>Should I wait to push updates to address your comments (e.g., const CPalette*, thorough self-checking) until after you have finished reviewing the initial PR?

Yes. Best to wait. I don't think there'll be much to do.

-Dale

2021-06-29 15:50 UTC, DLLarson requested changes
The only possible changes would be the addition of `const` to the palette pointers.

Code seems to operate fine when cursory tested against a variety of gamebox/games.

-Dale

2021-07-02 13:48 UTC, DLLarson approved these changes

2021-07-02 13:58 UTC, DLLarson commented
I'm conflicted on how to do the merge: collapse to a single commit or keep all the commits. 

Since it's your PR I'll defer to you for the choice.

-Dale

2021-07-03 02:12 UTC, wsu-cb commented
> I'm conflicted on how to do the merge: collapse to a single commit or keep all the commits.
> 
> Since it's your PR I'll defer to you for the choice.
> 
> -Dale

My preference is to keep all the commits.  I think it's easier to analyze what's going on when commits are smaller.

2021-07-03 02:27 UTC, merged