Type safety update for GameElement
CyberBoardPBEM/cbwindows pull request #56
Opened 2021-07-11 01:27 UTC by wsu-cb

Make the precise layout of GameElement more explicit in preparation for increasing ID width.

Fix #53

2021-07-11 15:08 UTC, DLLarson commented on GShr/DrawObj.h
> +    // KLUDGE:  release link fails if impl is in .cpp
Any idea why the link fails in this case? Does it seem like a compiler bug?

2021-07-11 15:17 UTC, DLLarson commented on GShr/MapStrng.cpp
> +    class GameElementCheck
What's this about? Is this some left over test code?

2021-07-11 15:23 UTC, DLLarson commented on GShr/MapStrng.h
> +typedef DWORD GameElementOld;
I'm confused about the role of `GameElementOld`. Sometimes it's used on debug builds. Sometimes not. Perhaps it's the name of the typedef.

2021-07-11 15:29 UTC, DLLarson requested changes
Some questions are "queued".

-Dale

2021-07-11 17:51 UTC, wsu-cb commented on GShr/DrawObj.h
> +    // KLUDGE:  release link fails if impl is in .cpp
At first glance, it kind of feels like a compiler bug.  However, I can actually imagine some reasons why forced inlining of a constexpr function makes sense.  I can do some experiments and see if a simpler example results in similar behavior, but it probably won't be today.

2021-07-11 17:57 UTC, wsu-cb commented on GShr/MapStrng.cpp
> +    class GameElementCheck
Test code, yes, but not leftover.  I wanted to leave this in long-term since other compilers and systems may use different bit layouts.

2021-07-11 18:06 UTC, wsu-cb commented on GShr/MapStrng.h
> +typedef DWORD GameElementOld;
The `GameElementOld` code is intended to be used consistently in debug builds to verify that the new code produces`GameElement` results that are binary-equal with the original code.  Where do you see it not being used in debug builds?

Since `ASSERT` doesn't do anything in release builds, I didn't see any reason to have any of the `GameElementOld` code run in release builds.

Unlike `GameElementCheck`, which is intended to check that files can be exchanged with new system ports, I expect to remove this code after a test period.

2021-07-11 18:50 UTC, DLLarson commented on GShr/MapStrng.cpp
> +    class GameElementCheck
Ok. Perhaps a comment about its purpose and longevity would've helped.

2021-07-11 18:55 UTC, DLLarson commented on GShr/MapStrng.h
> +inline GameElementOld MakeObjectIDElementOld(ObjectID dwObjectID)
This `GameElementOld` appears to be in the release build.

2021-07-11 18:55 UTC, DLLarson commented on GShr/MapStrng.h
> +        GameElementOld old = MakeMarkerElementOld(mid);
This `GameElementOld` appears to be in the release build.

2021-07-11 18:59 UTC, DLLarson commented on GShr/MapStrng.h
> +typedef DWORD GameElementOld;
This definition `GameElementOld` appears to be in the release build.

2021-07-11 19:03 UTC, DLLarson commented on GShr/MapStrng.h
> +typedef DWORD GameElementOld;
I think I'm really just having trouble wrapping my brain around the name. Perhaps something to the effect `GameElementLegacyCheck` or some such to capture its role rather than `Old`?

2021-07-11 19:07 UTC, DLLarson commented on GShr/DrawObj.h
> +    // KLUDGE:  release link fails if impl is in .cpp
Ok... no worries here.

2021-07-11 20:22 UTC, wsu-cb commented on GShr/MapStrng.cpp
> +    class GameElementCheck
I'm afraid I thought the "non-Microsoft field layout" text explained this.  However, I will add a more-explicit comment.

2021-07-11 20:24 UTC, wsu-cb commented on GShr/MapStrng.h
> +typedef DWORD GameElementOld;
Oops.  You're right; I missed that one.

2021-07-11 20:26 UTC, wsu-cb commented on GShr/MapStrng.h
> +inline GameElementOld MakeObjectIDElementOld(ObjectID dwObjectID)
And I missed that one.

2021-07-11 20:28 UTC, wsu-cb commented on GShr/MapStrng.h
> +        GameElementOld old = MakeMarkerElementOld(mid);
But I think this one is (as intended) only in debug.

2021-07-11 20:29 UTC, wsu-cb commented on GShr/MapStrng.h
> +typedef DWORD GameElementOld;
OK

2021-07-12 03:09 UTC, wsu-cb commented on GShr/DrawObj.h
> +    // KLUDGE:  release link fails if impl is in .cpp
(Draft) C++17 standard section 10.1.5 says constexpr functions are implicitly inline.  Therefore, it's more surprising when compilation succeeds rather than fails with the implementation in the .cpp.  Indeed, on a very simple project test, the linker failed in both debug and release builds when the implementation was in the .cpp.

So the real question is why does the Cyberboard debug link succeed?

But at any rate, I think the function does need to be inline.

2021-07-13 02:25 UTC, DLLarson commented
I ran into an ASSERT while testing the changes:

![image](https://user-images.githubusercontent.com/175455/125379593-68cead80-e356-11eb-973f-cc6be9f6e2e3.png)

To replicate use the attached archive.

[War1812-ASSERT-duringplayback-TestFiles.zip](https://github.com/CyberBoardPBEM/cbwindows/files/6805452/War1812-ASSERT-duringplayback-TestFiles.zip)

Load the game into the debug session of cbplay and do this:

![image](https://user-images.githubusercontent.com/175455/125380292-9536f980-e357-11eb-8826-9f801d172ff2.png)

-Dale

2021-07-13 04:46 UTC, wsu-cb commented
> I ran into an ASSERT while testing the changes:
> 

I see the problem, and how to fix it.  However, it's not related to this PR; this mistake has been (unnoticed) in master for a while.  Should I add the fix for this problem to this PR, or should I create a separate PR to fix this problem?

2021-07-13 13:20 UTC, DLLarson commented
>Should I add the fix for this problem to this PR, or should I create a separate PR to fix this problem?

Let's put it into a different PR then rather than cloud up this commit. 

l'll merge this one in. Would you prefer I retain all the commits or squash them with the squashed commit containing a roll-up of all the commits in its comment? i.e., Is there any value in this case with keeping the "sausage making"?

2021-07-13 21:11 UTC, wsu-cb commented
> l'll merge this one in. Would you prefer I retain all the commits or squash them with the squashed commit containing a roll-up of all the commits in its comment? i.e., Is there any value in this case with keeping the "sausage making"?

This is small enough that squashing seems reasonable.

2021-07-13 22:34 UTC, DLLarson approved these changes
Good to go!
-Dale

2021-07-13 22:35 UTC, merged