more attempts to explain ObjectId and GameElement behavior
CyberBoardPBEM/cbwindows pull request #60
Opened 2021-07-25 23:06 UTC by wsu-cb

This is some more work to attempt to explain how ObjectID and GameElement work.

Note that this makes use of undefined behavior, but I think it is extremely likely to work in practice.  (The code reads union members other than the active one, but the members are simple enough that I think it will work in practice.)

2021-07-26 14:22 UTC, DLLarson commented on GShr/DrawObj.h
> +    [[deprecated("only for GetObjectIDFromElementLegacyCheck()")]] explicit ObjectID(uint32_t dw);
I'm learning lots new here. [[deprecated]] is new to me. 

I'm glad the standard is adding things to replace custom attributes used by the different toolchains.

-Dale

2021-07-26 14:27 UTC, DLLarson commented on GShr/DrawObj.h
> +    GAMEELEM_MARKERID_FLAG, subtype 0x0 is pieceObjs,
The following couple of lines seem to give two defn's for subtype 0x0: "pieceObjs" and "subtype 0x0 is used as the invalid subtype code".

2021-07-26 14:32 UTC, DLLarson requested changes
I left some comments.

2021-07-26 14:38 UTC, DLLarson commented
I just did a test build and the debug version of CBDesign.exe asserts when starting up. CBPlay.exe doesn't assert.

-Dale

2021-07-27 01:05 UTC, wsu-cb commented on GShr/DrawObj.h
> +    GAMEELEM_MARKERID_FLAG, subtype 0x0 is pieceObjs,
Argh.  The enum Subtype farther down is correct; the comment is wrong.  New version to come...

2021-07-27 01:05 UTC, wsu-cb commented
> I just did a test build and the debug version of CBDesign.exe asserts when starting up. CBPlay.exe doesn't assert.
> 
> -Dale

Argh.  Nothing is too simple to do wrong.  New version to come.

2021-07-27 18:35 UTC, DLLarson requested changes
I see lots of warnings in the CBPlay.exe debug build...
```
1>------ Rebuild All started: Project: zLib, Configuration: Debug Win32 ------
:
:
1>uncompr.c
1>zutil.c
1>Generating Code...
1>zLib.vcxproj -> D:\Dev\CBoard\G\cbwindows\zLib\Debug\zLib.lib
2>------ Rebuild All started: Project: CBPlay, Configuration: Debug Win32 ------
2>StdAfx.cpp
2>Arclib.cpp
2>Atom.cpp
2>Board.cpp
2>D:\Dev\CBoard\G\cbwindows\GShr\MapStrng.h(385,14): warning C4996: 'ObjectID::ObjectID': only for GetObjectIDFromElementLegacyCheck()
2>BrdCell.cpp
2>D:\Dev\CBoard\G\cbwindows\GShr\MapStrng.h(385,14): warning C4996: 'ObjectID::ObjectID': only for GetObjectIDFromElementLegacyCheck()
:
:
2>DlgItray.cpp
2>D:\Dev\CBoard\G\cbwindows\gshr\MapStrng.h(385,14): warning C4996: 'ObjectID::ObjectID': only for GetObjectIDFromElementLegacyCheck()
2>DlgMarkCount.cpp
2>DlgMdesc.cpp
2>DlgMPly.cpp
2>DlgNewGeoBoard.cpp
2>D:\Dev\CBoard\G\cbwindows\gshr\MapStrng.h(385,14): warning C4996: 'ObjectID::ObjectID': only for GetObjectIDFromElementLegacyCheck()
:
:
2>Generating Code...
2>Compiling...
2>FrmPbrd.cpp
2>D:\Dev\CBoard\G\cbwindows\gshr\MapStrng.h(385,14): warning C4996: 'ObjectID::ObjectID': only for GetObjectIDFromElementLegacyCheck()
2>FrmProj.cpp
2>D:\Dev\CBoard\G\cbwindows\gshr\MapStrng.h(385,14): warning C4996: 'ObjectID::ObjectID': only for GetObjectIDFromElementLegacyCheck()
2>GamDoc.cpp
2>D:\Dev\CBoard\G\cbwindows\gshr\MapStrng.h(385,14): warning C4996: 'ObjectID::ObjectID': only for GetObjectIDFromElementLegacyCheck()
2>GamDoc1.cpp
2>D:\Dev\CBoard\G\cbwindows\gshr\MapStrng.h(385,14): warning C4996: 'ObjectID::ObjectID': only for GetObjectIDFromElementLegacyCheck()
2>GamDoc2.cpp
2>D:\Dev\CBoard\G\cbwindows\gshr\MapStrng.h(385,14): warning C4996: 'ObjectID::ObjectID': only for GetObjectIDFromElementLegacyCheck()
2>GamDoc3.cpp
2>D:\Dev\CBoard\G\cbwindows\gshr\MapStrng.h(385,14): warning C4996: 'ObjectID::ObjectID': only for GetObjectIDFromElementLegacyCheck()
2>GamDoc4.cpp
2>D:\Dev\CBoard\G\cbwindows\gshr\MapStrng.h(385,14): warning C4996: 'ObjectID::ObjectID': only for GetObjectIDFromElementLegacyCheck()
2>GamDoc5.cpp
2>D:\Dev\CBoard\G\cbwindows\gshr\MapStrng.h(385,14): warning C4996: 'ObjectID::ObjectID': only for GetObjectIDFromElementLegacyCheck()
2>GameBox.cpp
2>D:\Dev\CBoard\G\cbwindows\gshr\MapStrng.h(385,14): warning C4996: 'ObjectID::ObjectID': only for GetObjectIDFromElementLegacyCheck()
2>GamState.cpp
2>D:\Dev\CBoard\G\cbwindows\gshr\MapStrng.h(385,14): warning C4996: 'ObjectID::ObjectID': only for GetObjectIDFromElementLegacyCheck()
2>GdiTools.cpp
2>D:\Dev\CBoard\G\cbwindows\GShr\MapStrng.h(385,14): warning C4996: 'ObjectID::ObjectID': only for GetObjectIDFromElementLegacyCheck()
2>GeoBoard.cpp
2>D:\Dev\CBoard\G\cbwindows\gshr\MapStrng.h(385,14): warning C4996: 'ObjectID::ObjectID': only for GetObjectIDFromElementLegacyCheck()
2>Gp.cpp
2>D:\Dev\CBoard\G\cbwindows\gshr\MapStrng.h(385,14): warning C4996: 'ObjectID::ObjectID': only for GetObjectIDFromElementLegacyCheck()
:
:
2>WStateGp.cpp
2>D:\Dev\CBoard\G\cbwindows\gshr\MapStrng.h(385,14): warning C4996: 'ObjectID::ObjectID': only for GetObjectIDFromElementLegacyCheck()
2>Generating Code...
2>Arclib.obj : warning LNK4075: ignoring '/EDITANDCONTINUE' due to '/SAFESEH' specification
```

-Dale

2021-07-27 20:11 UTC, wsu-cb commented
> I see lots of warnings in the CBPlay.exe debug build...
> 
> ```
> 2>WStateGp.cpp
> 2>D:\Dev\CBoard\G\cbwindows\gshr\MapStrng.h(385,14): warning C4996: 'ObjectID::ObjectID': only for GetObjectIDFromElementLegacyCheck()
> ```
> 
> -Dale

Right.  Those are from `GetObjectIDFromElementLegacyCheck()`, which calls the deprecated `ObjectID::ObjectID(uint32_t dw)`.  If you recall an earlier discussion, I am currently still running (in debug mode) with some code in place to verify that the new `GameElement` code results in binary-equal results to the old code.  If you don't like seeing so many warnings, I can move the implementation of `GetObjectIDFromElementLegacyCheck()` out of the header to the implementation file, and that should result in only producing one warning.

2021-07-28 19:54 UTC, wsu-cb commented
> > I am currently still running (in debug mode) with some code in place to verify that the new GameElement code results in binary-equal results to the old code.
> 
> But if it verifies to be binary-equal why the warning? Shouldn't it indicate something is amiss? Am I missing something here?
> 
> -Dale

The new code is doing RUNTIME verification that the results rare binary-equal by having the new code generate its results, and then call the (renamed) old code and verify that the results are equal.  (I expect the new code to yield the same values, but I wanted to give it some more testing before I declared it correct.  I plan to remove the runtime check "soon-ish".)  The COMPILE TIME deprecation warning appears when the old code calls a function that is otherwise unnecessary and that I would like to remove due to type safety risks (and so marked deprecated).  However, as long as the old code is still being compared to the new code, I can't remove that (deprecated).  Maybe I should have marked the old `GameElement` code deprecated as well, but I think I unconsciously didn't bother because I was renaming it to "`Old`" (and then you suggested "`Legacy`") and "obviously" no new code would call "`Old`"/"`Legacy`" functions.

2021-07-29 22:14 UTC, DLLarson commented
Ok... If this is temporary I'm ok with that. Less output would be nice so when something else produces a warning it's not lost in the forest.

I'll merge if you are good to go. Your call.

-Dale

2021-07-30 02:05 UTC, wsu-cb commented
> Ok... If this is temporary I'm ok with that. Less output would be nice so when something else produces a warning it's not lost in the forest.
> 
> I'll merge if you are good to go. Your call.
> 
> -Dale

I pushed a commit to reduce the warnings as described in https://github.com/CyberBoardPBEM/cbwindows/pull/60#issuecomment-887802026.  I think it would be fine to squash all of this when you merge.

2021-07-30 16:21 UTC, DLLarson approved these changes

2021-07-30 16:22 UTC, merged