rewrite Atom code to be 64bit-clean
CyberBoardPBEM/cbwindows pull request #71
Opened 2021-10-02 22:44 UTC by wsu-cb

2021-10-04 14:17 UTC, DLLarson commented
Hi Bill,

I'll be checking this out in the next couple days. I also see I need to respond to the 64 bit issues in the issues section.

-Dale

2021-10-08 14:50 UTC, DLLarson commented
Note... I'm examining this PR on the individual commit level since they are so distinct.
-Dale

2021-10-08 16:01 UTC, DLLarson commented on GShr/FontName.cpp
>              return TRUE;
If we change return types to the C++ `bool` (a good thing except at Win32 APIs) should we being using the matching values of `true` and `false` to be consistent?

2021-10-09 05:11 UTC, wsu-cb commented on GShr/Atom.h
>  #ifndef _ATOM_H
OK

2021-10-09 05:28 UTC, wsu-cb commented on GShr/FontName.cpp
> +            return size_t(TRUE);
I thought about rewriting this code to be a little less overloaded, but didn't in an effort to keep it easier to do the comparison to the original code.  However, since you are independently suggesting a cleaner interface would be good, I will work on that.

2021-10-09 05:36 UTC, wsu-cb commented on GShr/FontName.cpp
>              return TRUE;
Since TRUE and FALSE have values 1 and 0, it would be very unusual to get in trouble by using them, so I tend to avoid changing then to make history comparison easier.  However, BOOL/TRUE/FALSE Microsoft specific, so again we should be getting rid of them over time.  (If I remember right, I could not put off changing some BOOL to bool to deal with integer type issues when turning on stricter warning checks.)

2021-10-09 13:59 UTC, DLLarson commented on GShr/FontName.cpp
> +            lstrcpy(pszFName, fname.szFName);
I guess I'm saying my desire is to stay the hell away from 16 and 32 bit characters. Window is finally seeing some support for UTF8 but only recently. We struggled with this issue in embedded controllers all the time. It's a PITA. But in the future support for other languages would be a good thing. Unfortunate STL still has only limited support for utf8 conversions as well. The std::string is just byte arrays.  We had to write our own processing in our microcontrollers. String comparisons, strlen, etc all need special processing. So I'm not saying it's easy--it's not. But things seem to be heading in that direction albeit slowly. 

I really wouldn't want to see the app use wide strings which turn out to be 32 bits in *nix platforms and 16 bits in windows.

2021-10-10 05:23 UTC, wsu-cb commented on GShr/Atom.h
>  #ifndef _ATOM_H
done

2021-10-10 05:26 UTC, wsu-cb commented on GShr/FontName.cpp
> +            return size_t(TRUE);
I discovered that this function is actually unused.  Nevertheless, I have replaced it, but the change is pretty drastic.  Let's see how you like it.

2021-10-16 18:10 UTC, DLLarson commented
>I discovered that this function is actually unused. Nevertheless, I have replaced it, but the change is pretty drastic. Let's see how you like it.

Probably because I wrote it as a general facility and guessed at what was needed. Looks good to me now.

-Dale

2021-10-16 18:12 UTC, DLLarson requested changes
Looks good. Only missing a minor indent formatting issue.

-Dale

2021-10-17 14:57 UTC, DLLarson approved these changes
Good to go.

2021-10-17 14:57 UTC, merged