Create many-sided pieces
CyberBoardPBEM/cbwindows pull request #81
Opened 2022-04-06 04:53 UTC by wsu-cb

This is the first step to support pieces with many sides (Enhancement #14).  It allows CBDesign to create and edit pieces with many sides.  The list boxes can show all the sides, but most of the rest of the system doesn't support the extra sides yet.

Dale, please let me know what you think of this so far.

2022-04-09 20:50 UTC, DLLarson commented
Hi Bill,

I'll be looking this over in the next few days.

-Dale

2022-04-09 22:42 UTC, DLLarson commented on GM/DlgPedt.cpp
> +    m_pTMgr(*m_pDoc->GetTileManager()),
Just strange looking that these near identically named members (`m_pTMgr` and `m_pPMgr`) used different looking levels of indirection.

2022-04-09 23:15 UTC, wsu-cb commented on GM/DlgPedt.cpp
> +    m_pTMgr(*m_pDoc->GetTileManager()),
1)  When I change the type of a variable, I generally try to avoid changing its name.  I think it makes it easier to understand what I readily admit are pretty extensive changes.
2)  I generally try to use the most restrictive type that still permits the code to compile.

So we wind up with inconsistencies like this for pre-existing variables.  I acknowledge that not changing the name now may create confusion in the future when someone looks at the replacement code without looking at the previous code.

If you want me to remove the `p` markers when I change something into a reference in the future, I can try to remember that, but I think it will make diffs harder to understand.  At the cost of making even larger pull requests, another option is to make two commits, one like the ones I currently make, and a follow-up commit that removes obsolete `p` marks.  I think that will keep the individual commits easier to understand, but obviously creates even more commits and larger pull requests.

2022-04-10 01:07 UTC, DLLarson commented on GM/DlgPedt.cpp
> +    m_pTMgr(*m_pDoc->GetTileManager()),
Forget all that. It was just a gut reaction. It's fine as is.

There is much bigger fish to fry.

-Dale

2022-04-11 17:06 UTC, DLLarson commented on GShr/Versions.h
> +                if (bFlag && strcmp(pszParam, "id32cb64sidemany") == 0)
Question... Should I be specifying `/id32cb64sidemany` when I run the app for multifaced operation?

-Dale

2022-04-12 00:07 UTC, wsu-cb commented on GShr/Versions.h
> +                if (bFlag && strcmp(pszParam, "id32cb64sidemany") == 0)
If you just want to create and edit many-sided pieces, you don't need the switch.  However, you will need it to save a file with many-sided pieces.  Presumably, you will typically want to save your work, so I would typically run with the switch.

(I changed /id32cb64 to /id32cb64sidemany as in indicator that the current file format is no longer compatible with the previous file format 4.0.  One-or-two-sided pieces can still be saved in CB3.1 format.)

2022-04-12 13:36 UTC, DLLarson commented on GShr/Versions.h
> +                if (bFlag && strcmp(pszParam, "id32cb64sidemany") == 0)
Hi Bill,

I've had a chance to scan the code and I think you're starting in a good place. Obviously the most challenging thing is accounting for the multi-side stuff throughout the UI such that it operates in sane and intuitive fashion. I think it's wise to retain the concept of a top side as it is the anchor point of a piece. Expanding the single back side into multiples makes sense.

I was thinking of unusual use cases for this and modeling a multi-faced die having special images for each face came to mind. It would be cool to be able to pull a piece out of a tray and have it result in a random side selection. I'm sure people will think up all kinds of applications for multi-sided pieces that wander far from representing more piece information for instance. It should be interesting.

I say charge ahead!

I'm assuming that we shouldn't fold this into `master` yet. In fact we may want to create a global working branch so we can collect inspected PR's in one place without risking damaging the main code until it's ready. That would be easier to manage than a constantly expanding a single PR.

-Dale

2022-04-13 00:41 UTC, wsu-cb commented on GShr/Versions.h
> +                if (bFlag && strcmp(pszParam, "id32cb64sidemany") == 0)
> Hi Bill,
> 
> I've had a chance to scan the code and I think you're starting in a good place. Obviously the most challenging thing is accounting for the multi-side stuff throughout the UI such that it operates in sane and intuitive fashion. I think it's wise to retain the concept of a top side as it is the anchor point of a piece. Expanding the single back side into multiples makes sense.
> 
> I was thinking of unusual use cases for this and modeling a multi-faced die having special images for each face came to mind. It would be cool to be able to pull a piece out of a tray and have it result in a random side selection. I'm sure people will think up all kinds of applications for multi-sided pieces that wander far from representing more piece information for instance. It should be interesting.
> 

As I said in Issue #14, the non-standard War of the Ring dice were one of my specific motivations for this work.

I certainly think it would make sense to give the trays the option to put a piece on a random side when pulled from the tray.  However, I plan to put a context menu on pieces in the selected-piece window that will allow choosing a random side (for dice), as well as flipping the piece to the side where the user brought up the menu (for strength-point style pieces).

> I say charge ahead!
> 
> I'm assuming that we shouldn't fold this into `master` yet. In fact we may want to create a global working branch so we can collect inspected PR's in one place without risking damaging the main code until it's ready. That would be easier to manage than a constantly expanding a single PR.
> 
> -Dale

I definitely don't want this merged to master any time soon.  I posted it now because this is so different from the relatively minor (in terms of concept, not lines of code) changes I had been making in previous PRs.  I wanted to be sure you approved the general direction I am going.

I think a feature branch would make a lot of sense for this.  However, I am likely to make a lot of force pushes to the branch.  In my previous PRs, I had always kept my branches local and done a lot of rebase clean-up work before pushing for review.  If I push to github earlier, those rebases won't be just on my local repo.  There is the middle ground of keeping the feature branch only in my fork, and doing the rebases there, and only sending a PR to the main CB repo when I am ready for your review.  What's your preference?

2022-04-13 16:05 UTC, DLLarson commented
>There is the middle ground of keeping the feature branch only in my fork, and doing the rebases there, and only sending a PR to the main CB repo when I am ready for your review.

I think this approach would be fine. You'll have your local copy and a backup in your fork just-in-case. When ready just post to the PR.

I'm just trying to avoid reinspection of code I've already looked at. I understand that this is somewhat tough to avoid since the same source code files will evolve along with the additional UI (etc...) work so they will show up again. But the adding new features should definitely trump my discomfort with redundancy. ;)

-Dale

2022-07-13 17:06 UTC, DLLarson requested changes
Whew! That was a heap 'o code to get through!

I'd like to run the code against some files. Have you cooked up any test files for these changes?
It would save me some time trying out the features.

-Dale

2022-07-16 04:48 UTC, wsu-cb commented on GP/PalTray.cpp
> +    CArray<int, int> tblListSubjects;
I think it was because tblListSubjects has to have the same type as tblListSel, and there was no specific need to change tblListSel.

2022-07-16 05:32 UTC, wsu-cb commented on GShr/CyberBoard.h
> +{
There was quite a bit of v3.1 code that was the same between `CMarkManager`, `CPieceManager`, and `CTileManager`, so I consolidated that code into a template.  At the time, I thought the `Serialize()` code for `CTileManager` differed from `CMarkManager` and `CPieceManager` in using #ifdef to skip the save of the ID table in GPlay, so I used this template argument to address that distinction.  However, in reviewing the code today to write this comment, I now think both the v3.1 code and the new code use #ifdef in a way that means XxxxID<TileID>::Serialize() is never even called when saving in GPlay, and that this argument is therefore unnecessary.  Whoops.

2022-07-16 05:39 UTC, wsu-cb commented on GShr/LBoxMark.cpp
> +    CString& strTip, CString& strTitle) const
It looks to me like you were allowing for the possibility of using `TTM_SETTITLE`, but that no code ever actually took advantage of that option.

2022-07-31 18:17 UTC, DLLarson approved these changes

2022-07-31 18:18 UTC, DLLarson commented
I approved the code changes but I'm pretty sure you don't want them merged to master yet.

Am I correct?

-Dale

2022-07-31 18:49 UTC, wsu-cb commented
> I approved the code changes but I'm pretty sure you don't want them merged to master yet.
> 
> Am I correct?
> 
> -Dale

Actually, I think this PR is ready for merge.  I have done some testing of it, and really serious testing will probably be done only after I create `.gam`s for Space Empires that will also make use of #86.  Unfortunately, building the `Space Empires.gbx` isn't a quick process.

2022-07-31 19:34 UTC, DLLarson commented
>Actually, I think this PR is ready for merge. I have done some testing of it, and really serious testing will probably be done only after I create .gams for Space Empires that will also make use of https://github.com/CyberBoardPBEM/cbwindows/issues/86.

Ok! To master it is.

An exciting moment!

-Dale

2022-07-31 19:35 UTC, merged