Owned board hidden movement
CyberBoardPBEM/cbwindows pull request #87
Opened 2022-09-04 20:34 UTC by wsu-cb

Resolve #86

2022-09-05 02:05 UTC, wsu-cb commented
Drat.  After more testing, I would like to change the playback display when flipping owned pieces.  Therefore, I have converted this PR to a draft.

2022-09-19 23:27 UTC, wsu-cb commented on GP/GamDoc.cpp
> +        while ((m_nCurMove = m_pMoves->DoMove(*this, m_nCurMove)) < nPrvMove &&
I'm somewhat concerned about this change.  I don't understand what situation the original code's `FALSE` was handling, so I don't know whether this change could be causing a problem.

2022-09-20 15:50 UTC, DLLarson requested changes
I just had some questions.

2022-09-20 15:50 UTC, DLLarson commented on GP/GamDoc3.cpp
> -            NumVersion(fileGsnVerMajor, fileGsnVerMinor) &&
Why the switch from `...Gsn...` to `...Gmv...`?
Was this a bug?

2022-09-20 15:50 UTC, DLLarson commented on GP/GameBox.cpp
> +            NumVersion(fileGbxVerMajor, fileGbxVerMinor) &&
Same question about why this changed. Bug?

2022-09-20 15:50 UTC, DLLarson commented on GShr/LBoxGfx2.cpp
> +        SendMessage(WM_HSCROLL, MAKELONG(int16_t(SB_THUMBPOSITION), value_preserving_cast<int16_t>(horzScroll)), NULL);
Was this for a bug?

2022-09-20 15:50 UTC, DLLarson commented on GShr/LBoxGrfx.h
> +            SendMessage(WM_HSCROLL, MAKELONG(int16_t(SB_THUMBPOSITION), value_preserving_cast<int16_t>(horzScroll)), NULL);
Was this for a bug?

2022-09-20 15:50 UTC, DLLarson commented on GShr/Versions.h
> +                static const std::regex re(R"(filever:([[:digit:]]+)\.([[:digit:]]+))");
My first look at the `regex` support. Nice!

2022-09-20 15:51 UTC, DLLarson commented on GP/GamDoc.cpp
> +        while ((m_nCurMove = m_pMoves->DoMove(*this, m_nCurMove)) < nPrvMove &&
I'm not clear on the issue here.

2022-09-21 00:44 UTC, wsu-cb commented on GShr/LBoxGfx2.cpp
> +        SendMessage(WM_HSCROLL, MAKELONG(int16_t(SB_THUMBPOSITION), value_preserving_cast<int16_t>(horzScroll)), NULL);
Yes.  See https://github.com/CyberBoardPBEM/cbwindows/pull/87/commits/de96b8333c9cd5a71fbb1c8e343c55dfc3d5fd46.  (`SetScrollPos()` moved the scroll thumb without actually changing the visible portion of the window!)

2022-09-21 00:45 UTC, wsu-cb commented on GShr/LBoxGrfx.h
> +            SendMessage(WM_HSCROLL, MAKELONG(int16_t(SB_THUMBPOSITION), value_preserving_cast<int16_t>(horzScroll)), NULL);
See https://github.com/CyberBoardPBEM/cbwindows/pull/87#discussion_r975920329.

2022-09-21 00:49 UTC, wsu-cb commented on GP/GameBox.cpp
> +            NumVersion(fileGbxVerMajor, fileGbxVerMinor) &&
This code is reading a `.gbx`, so I do think it should be checking against `fileGbxVerMajor`/`fileGbxVerMinor`.

2022-09-21 00:53 UTC, wsu-cb commented on GP/GamDoc3.cpp
> -            NumVersion(fileGsnVerMajor, fileGsnVerMinor) &&
This code is reading a `.gmv`, so I think checking `fileGmvVerMajor`/`fileGmvVerMinor` is more appropriate.

2022-09-21 00:59 UTC, wsu-cb commented on GP/GamDoc.cpp
> +        while ((m_nCurMove = m_pMoves->DoMove(*this, m_nCurMove)) < nPrvMove &&
I'm sorry; I can't tell if you mean you don't understand my comment, or if you mean you don't remember why the original code used `FALSE`.

2022-09-21 18:11 UTC, DLLarson commented on GShr/LBoxGfx2.cpp
> +        SendMessage(WM_HSCROLL, MAKELONG(int16_t(SB_THUMBPOSITION), value_preserving_cast<int16_t>(horzScroll)), NULL);
Dang! Nice find!

2022-10-13 04:15 UTC, wsu-cb commented
Dale, are you still reviewing this?

2022-10-13 12:52 UTC, DLLarson commented
I just had some questions in the review before merging (see above about back stepping. That's why I didn't pull the trigger on the merge.

-Dale

2022-10-13 23:17 UTC, wsu-cb commented
> I just had some comments in the review before merging (see above about back stepping) so I wanted to see if you were good with them. That's why I didn't pull the trigger on the merge.

Did you see https://github.com/CyberBoardPBEM/cbwindows/pull/87#discussion_r975936237?

2022-10-14 16:42 UTC, DLLarson commented
> > I just had some comments in the review before merging (see above about back stepping) so I wanted to see if you were good with them. That's why I didn't pull the trigger on the merge.
> 
> Did you see [#87 (comment)](https://github.com/CyberBoardPBEM/cbwindows/pull/87#discussion_r975936237)?

Yes and I replied with this:

>so this code is the move back a step processing. It goes back to one move before the move we're stepping back to so it can replay it to get to the desired state. This code is tricky and my memory is definitely fuzzy here but this comment:

        // OK...we know there is at least one move to do PRIOR to the move
        // we are stepping up to. Find it so we can turn off silent mode for
        // that move.
>seems to suggest that the argument bAutoStepHiddenMove value should be overridden with FALSE so that move is visible.

So the code changes seems to reverse what the code did before (by default initialization) and I feel this may be wrong so--as a minimum-- I expected you to react to that as it seems wrong.

-Dale

2022-10-15 15:04 UTC, DLLarson approved these changes

2022-10-15 20:05 UTC, DLLarson approved these changes
Looks good.

2022-10-15 20:06 UTC, merged